"""initial currency schema

Revision ID: cc6072dfa82c
Revises: 
Create Date: 2026-03-19 17:10:21.442807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6072dfa82c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_exchange_rates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cer_lookup', 'currency_exchange_rates', ['company_id', 'base_currency', 'target_currency', sa.text('captured_at DESC')], unique=False)
    op.create_index(op.f('ix_currency_exchange_rates_company_id'), 'currency_exchange_rates', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_exchange_rates_company_id'), table_name='currency_exchange_rates')
    op.drop_index('ix_cer_lookup', table_name='currency_exchange_rates')
    op.drop_table('currency_exchange_rates')
    # ### end Alembic commands ###
