[alembic]
# Esta es la ruta absoluta dentro del contenedor tras montar la carpeta /backend
script_location = alembic

version_path_separator = os

# URL de conexión (Asegúrate de que coincida con tu docker-compose)
sqlalchemy.url = postgresql+asyncpg://user:password@postgres-db:5432/master_data_db

[post_write_hooks]
# Opcional: formateo de código tras crear migraciones
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = REVISION_SCRIPT_FILE

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S