from enum import Enum

class SubscriptionStatus(str, Enum):
    TRIAL = "TRIAL"
    ACTIVE = "ACTIVE"
    PAST_DUE = "PAST_DUE"
    RESTRICTED = "RESTRICTED"
    UNPAID = "UNPAID"
    EXPIRED = "EXPIRED"
    CANCELED = "CANCELED"

class ModuleCode(str, Enum):
    AUTH_CORE = "AUTH_CORE"
    INVENTORY_CORE = "INVENTORY_CORE"
    MES_CORE = "MES_CORE"
    WMS_CORE = "WMS_CORE"
    TICKETS_CORE = "TICKETS_CORE"
    HCM_CORE = "HCM_CORE"
    MAINTENANCE_CORE = "MAINTENANCE_CORE"
