"""initial_schema

Revision ID: 2f5f0376f68f
Revises: 
Create Date: 2026-04-12 17:18:30.645288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5f0376f68f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_photos',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('guest_session_id', sa.String(length=128), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('thumb_key', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'APPROVED', 'REJECTED', 'PURCHASED', 'PRINTING', 'DONE', name='photo_status'), nullable=False),
    sa.Column('approval_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_photos_company_id'), 'event_photos', ['company_id'], unique=False)
    op.create_index(op.f('ix_event_photos_event_id'), 'event_photos', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_photos_guest_session_id'), 'event_photos', ['guest_session_id'], unique=False)
    op.create_index(op.f('ix_event_photos_status'), 'event_photos', ['status'], unique=False)
    op.create_table('kiosk_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('photo_price', sa.Integer(), nullable=False),
    sa.Column('rule_paparazzi', sa.Boolean(), nullable=False),
    sa.Column('watermark_key', sa.String(length=512), nullable=True),
    sa.Column('required_approvals', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('payment_orders',
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('guest_session_id', sa.String(length=128), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.Enum('STRIPE', 'CASH', 'WALLET', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='payment_status'), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=128), nullable=True),
    sa.Column('stripe_client_secret', sa.String(length=256), nullable=True),
    sa.Column('cash_qr_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['event_photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_qr_token')
    )
    op.create_index(op.f('ix_payment_orders_company_id'), 'payment_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_payment_orders_event_id'), 'payment_orders', ['event_id'], unique=False)
    op.create_index(op.f('ix_payment_orders_photo_id'), 'payment_orders', ['photo_id'], unique=False)
    op.create_index(op.f('ix_payment_orders_status'), 'payment_orders', ['status'], unique=False)
    op.create_table('photo_approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('approver_index', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['event_photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id', 'approver_index', name='uq_photo_approver_index'),
    sa.UniqueConstraint('photo_id', 'device_id', name='uq_photo_device_id')
    )
    op.create_index(op.f('ix_photo_approvals_photo_id'), 'photo_approvals', ['photo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_approvals_photo_id'), table_name='photo_approvals')
    op.drop_table('photo_approvals')
    op.drop_index(op.f('ix_payment_orders_status'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_photo_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_event_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_company_id'), table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_table('kiosk_events')
    op.drop_index(op.f('ix_event_photos_status'), table_name='event_photos')
    op.drop_index(op.f('ix_event_photos_guest_session_id'), table_name='event_photos')
    op.drop_index(op.f('ix_event_photos_event_id'), table_name='event_photos')
    op.drop_index(op.f('ix_event_photos_company_id'), table_name='event_photos')
    op.drop_table('event_photos')
    # ### end Alembic commands ###
