"""audit_hardening

Revision ID: 86a6ad039d59
Revises: 42ea522fc124
Create Date: 2026-03-25 17:32:43.295369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a6ad039d59'
down_revision: Union[str, None] = '42ea522fc124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('inventory_stocks',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('uom_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', 'company_id', name='uq_warehouse_product_tenant')
    )
    op.create_index(op.f('ix_inventory_stocks_company_id'), 'inventory_stocks', ['company_id'], unique=False)
    op.create_index(op.f('ix_inventory_stocks_group_id'), 'inventory_stocks', ['group_id'], unique=False)
    op.create_index(op.f('ix_inventory_stocks_product_id'), 'inventory_stocks', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_stocks_tenant_id'), 'inventory_stocks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_stocks_uom_id'), 'inventory_stocks', ['uom_id'], unique=False)
    op.create_index(op.f('ix_inventory_stocks_warehouse_id'), 'inventory_stocks', ['warehouse_id'], unique=False)
    op.create_table('stock_lots',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_lots_batch_number'), 'stock_lots', ['batch_number'], unique=False)
    op.create_index(op.f('ix_stock_lots_company_id'), 'stock_lots', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_lots_group_id'), 'stock_lots', ['group_id'], unique=False)
    op.create_index(op.f('ix_stock_lots_product_id'), 'stock_lots', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_lots_tenant_id'), 'stock_lots', ['tenant_id'], unique=False)
    op.add_column('file_metadata', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_file_metadata_tenant_id'), 'file_metadata', ['tenant_id'], unique=False)
    op.add_column('inter_company_transfers', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_inter_company_transfers_tenant_id'), 'inter_company_transfers', ['tenant_id'], unique=False)
    op.drop_column('inter_company_transfers', 'cost_b_amount')
    op.drop_column('inter_company_transfers', 'wac_origin_amount')
    op.drop_column('inter_company_transfers', 'unit_price_amount')
    op.drop_column('inter_company_transfers', 'revenue_a_amount')
    op.add_column('inventory_backflush_errors', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_inventory_backflush_errors_tenant_id'), 'inventory_backflush_errors', ['tenant_id'], unique=False)
    op.add_column('inventory_boms', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_inventory_boms_tenant_id'), 'inventory_boms', ['tenant_id'], unique=False)
    op.add_column('inventory_documents', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.alter_column('inventory_documents', 'external_reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_inventory_documents_external_reference'), 'inventory_documents', ['external_reference'], unique=True)
    op.create_index(op.f('ix_inventory_documents_tenant_id'), 'inventory_documents', ['tenant_id'], unique=False)
    op.add_column('inventory_item_variants', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_inventory_item_variants_tenant_id'), 'inventory_item_variants', ['tenant_id'], unique=False)
    op.add_column('inventory_levels', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_inventory_levels_tenant_id'), 'inventory_levels', ['tenant_id'], unique=False)
    op.add_column('inventory_movement_concepts', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_inventory_movement_concepts_tenant_id'), 'inventory_movement_concepts', ['tenant_id'], unique=False)
    op.add_column('inventory_movements', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_inventory_movements_tenant_id'), 'inventory_movements', ['tenant_id'], unique=False)
    op.drop_column('inventory_movements', 'unit_price_amount')
    op.add_column('inventory_transactions', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_inventory_transactions_tenant_id'), 'inventory_transactions', ['tenant_id'], unique=False)
    op.add_column('inventory_warehouses', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_inventory_warehouses_tenant_id'), 'inventory_warehouses', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_warehouses_tenant_id'), table_name='inventory_warehouses')
    op.drop_column('inventory_warehouses', 'tenant_id')
    op.drop_index(op.f('ix_inventory_transactions_tenant_id'), table_name='inventory_transactions')
    op.drop_column('inventory_transactions', 'tenant_id')
    op.add_column('inventory_movements', sa.Column('unit_price_amount', sa.NUMERIC(precision=18, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_inventory_movements_tenant_id'), table_name='inventory_movements')
    op.drop_column('inventory_movements', 'tenant_id')
    op.drop_index(op.f('ix_inventory_movement_concepts_tenant_id'), table_name='inventory_movement_concepts')
    op.drop_column('inventory_movement_concepts', 'tenant_id')
    op.drop_index(op.f('ix_inventory_levels_tenant_id'), table_name='inventory_levels')
    op.drop_column('inventory_levels', 'tenant_id')
    op.drop_index(op.f('ix_inventory_item_variants_tenant_id'), table_name='inventory_item_variants')
    op.drop_column('inventory_item_variants', 'tenant_id')
    op.drop_index(op.f('ix_inventory_documents_tenant_id'), table_name='inventory_documents')
    op.drop_index(op.f('ix_inventory_documents_external_reference'), table_name='inventory_documents')
    op.alter_column('inventory_documents', 'external_reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('inventory_documents', 'tenant_id')
    op.drop_index(op.f('ix_inventory_boms_tenant_id'), table_name='inventory_boms')
    op.drop_column('inventory_boms', 'tenant_id')
    op.drop_index(op.f('ix_inventory_backflush_errors_tenant_id'), table_name='inventory_backflush_errors')
    op.drop_column('inventory_backflush_errors', 'tenant_id')
    op.add_column('inter_company_transfers', sa.Column('revenue_a_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True))
    op.add_column('inter_company_transfers', sa.Column('unit_price_amount', sa.NUMERIC(precision=18, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('inter_company_transfers', sa.Column('wac_origin_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True))
    op.add_column('inter_company_transfers', sa.Column('cost_b_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_inter_company_transfers_tenant_id'), table_name='inter_company_transfers')
    op.create_index('ix_ict_status', 'inter_company_transfers', ['status'], unique=False)
    op.create_index('ix_ict_product_id', 'inter_company_transfers', ['product_id'], unique=False)
    op.create_index('ix_ict_mirror_document_id', 'inter_company_transfers', ['mirror_document_id'], unique=False)
    op.create_index('ix_ict_destination_company_id', 'inter_company_transfers', ['destination_company_id'], unique=False)
    op.create_index('ix_ict_company_id', 'inter_company_transfers', ['company_id'], unique=False)
    op.drop_column('inter_company_transfers', 'tenant_id')
    op.drop_index(op.f('ix_file_metadata_tenant_id'), table_name='file_metadata')
    op.drop_column('file_metadata', 'tenant_id')
    op.drop_index(op.f('ix_stock_lots_tenant_id'), table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_product_id'), table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_group_id'), table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_company_id'), table_name='stock_lots')
    op.drop_index(op.f('ix_stock_lots_batch_number'), table_name='stock_lots')
    op.drop_table('stock_lots')
    op.drop_index(op.f('ix_inventory_stocks_warehouse_id'), table_name='inventory_stocks')
    op.drop_index(op.f('ix_inventory_stocks_uom_id'), table_name='inventory_stocks')
    op.drop_index(op.f('ix_inventory_stocks_tenant_id'), table_name='inventory_stocks')
    op.drop_index(op.f('ix_inventory_stocks_product_id'), table_name='inventory_stocks')
    op.drop_index(op.f('ix_inventory_stocks_group_id'), table_name='inventory_stocks')
    op.drop_index(op.f('ix_inventory_stocks_company_id'), table_name='inventory_stocks')
    op.drop_table('inventory_stocks')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
