"""Add photo_path to item_variants

Revision ID: a5c404f77598
Revises: b866e852ddc4
Create Date: 2026-04-16 18:55:59.481660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c404f77598'
down_revision: Union[str, None] = 'b866e852ddc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_item_variants', sa.Column('photo_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_item_variants', 'photo_path')
    # ### end Alembic commands ###
