from pydantic import BaseModel, Field
from decimal import Decimal
import uuid
from typing import Optional

class StockBase(BaseModel):
    warehouse_id: uuid.UUID
    product_id: uuid.UUID
    quantity: Decimal = Field(default=0)
    reserved_quantity: Decimal = Field(default=0)

class StockRead(StockBase):
    id: uuid.UUID
    company_id: uuid.UUID

    class Config:
        from_attributes = True

class MovementCreate(BaseModel):
    warehouse_id: uuid.UUID
    product_id: uuid.UUID
    quantity: Decimal
    movement_type: str # IN, OUT, ADJUSTMENT
    document_type: str
    document_id: uuid.UUID
    unit_price: Decimal = Decimal("0.0")
    currency: str = "MXN"
    customs_pedimento_id: Optional[uuid.UUID] = None

class StockReserveCmd(BaseModel):
    warehouse_id: uuid.UUID
    product_id: uuid.UUID
    quantity: Decimal

class TransferDispatchCmd(BaseModel):
    from_warehouse_id: uuid.UUID
    to_warehouse_id: uuid.UUID
    product_id: uuid.UUID
    quantity: Decimal
    uom_id: uuid.UUID
    weight: Decimal = Decimal("0.0")  # Optional — defaults to 0 for intra-company ops
    transfer_id: Optional[uuid.UUID] = None  # Auto-generated by endpoint if not provided
    selected_batch_id: Optional[uuid.UUID] = None

class TransferReceiveCmd(BaseModel):
    from_warehouse_id: uuid.UUID
    to_warehouse_id: uuid.UUID
    product_id: uuid.UUID
    quantity: Decimal
    uom_id: uuid.UUID
    weight: Decimal = Decimal("0.0")  # Optional — defaults to 0
    transfer_id: Optional[uuid.UUID] = None  # Auto-generated by endpoint if not provided
    customs_pedimento_id: Optional[uuid.UUID] = None

class CycleCountItem(BaseModel):
    product_id: uuid.UUID
    sku: str
    difference: Decimal
    status: str

class CycleCountPayload(BaseModel):
    location: str
    items: list[CycleCountItem]
