"""Add audit_logs table and trace_id

Revision ID: 275265eb5f75
Revises: 765d720a47b1
Create Date: 2026-02-28 17:50:10.443832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275265eb5f75'
down_revision = '765d720a47b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('record_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.String(length=100), nullable=True),
    sa.Column('group_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
