"""Add BusinessGroup and multi-tenant Audit logs

Revision ID: 343aa6145185
Revises: 3bcb25af8d1c
Create Date: 2026-02-28 17:24:28.531312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343aa6145185'
down_revision = '3bcb25af8d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_groups_name'), 'business_groups', ['name'], unique=False)
    op.create_foreign_key(None, 'companies', 'business_groups', ['parent_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_business_groups_name'), table_name='business_groups')
    op.drop_table('business_groups')
    # ### end Alembic commands ###