"""fix_role_permission_uniqueness

Revision ID: 5902da5eece9
Revises: f5945e39ddc3
Create Date: 2026-02-28 18:59:21.535491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5902da5eece9'
down_revision = 'f5945e39ddc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('permissions_name_key', 'permissions', type_='unique')
    op.create_unique_constraint('uq_permission_name_company', 'permissions', ['name', 'company_id'])
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_unique_constraint('uq_role_name_company', 'roles', ['name', 'company_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_role_name_company', 'roles', type_='unique')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_constraint('uq_permission_name_company', 'permissions', type_='unique')
    op.create_unique_constraint('permissions_name_key', 'permissions', ['name'])
    # ### end Alembic commands ###