"""Add_tenant_id

Revision ID: 6951cac9a0d8
Revises: d1a4f83cbe7a
Create Date: 2026-03-25 20:37:18.100636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6951cac9a0d8'
down_revision = 'd1a4f83cbe7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_file_metadata_tenant_id'), 'file_metadata', ['tenant_id'], unique=False)
    op.add_column('invitations', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invitations_tenant_id'), 'invitations', ['tenant_id'], unique=False)
    op.add_column('permissions', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_permissions_tenant_id'), 'permissions', ['tenant_id'], unique=False)
    op.add_column('refresh_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('refresh_tokens', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('refresh_tokens', sa.Column('transaction_id', sa.UUID(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('version_id', sa.Integer(), nullable=False))
    op.drop_index('ix_refresh_tokens_hash', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_company', table_name='refresh_tokens')
    op.drop_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_company_id'), 'refresh_tokens', ['company_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.add_column('role_permissions', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_role_permissions_tenant_id'), 'role_permissions', ['tenant_id'], unique=False)
    op.add_column('roles', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.add_column('user_company_roles', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_user_company_roles_tenant_id'), 'user_company_roles', ['tenant_id'], unique=False)
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    op.drop_index(op.f('ix_user_company_roles_tenant_id'), table_name='user_company_roles')
    op.drop_column('user_company_roles', 'tenant_id')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_column('roles', 'tenant_id')
    op.drop_index(op.f('ix_role_permissions_tenant_id'), table_name='role_permissions')
    op.drop_column('role_permissions', 'tenant_id')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_company_id'), table_name='refresh_tokens')
    op.create_unique_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', ['token_hash'])
    op.create_index('ix_refresh_tokens_user_company', 'refresh_tokens', ['user_id', 'company_id'], unique=False)
    op.create_index('ix_refresh_tokens_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.drop_column('refresh_tokens', 'version_id')
    op.drop_column('refresh_tokens', 'is_active')
    op.drop_column('refresh_tokens', 'transaction_id')
    op.drop_column('refresh_tokens', 'deleted_at')
    op.drop_column('refresh_tokens', 'updated_by')
    op.drop_column('refresh_tokens', 'created_by')
    op.drop_column('refresh_tokens', 'updated_at')
    op.drop_index(op.f('ix_permissions_tenant_id'), table_name='permissions')
    op.drop_column('permissions', 'tenant_id')
    op.drop_index(op.f('ix_invitations_tenant_id'), table_name='invitations')
    op.drop_column('invitations', 'tenant_id')
    op.drop_index(op.f('ix_file_metadata_tenant_id'), table_name='file_metadata')
    op.drop_column('file_metadata', 'tenant_id')
    # ### end Alembic commands ###
