"""Add trace_id to audit_logs

Revision ID: 765d720a47b1
Revises: 343aa6145185
Create Date: 2026-02-28 17:49:12.420774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '765d720a47b1'
down_revision = '343aa6145185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Safe drop if exists
    op.execute('DROP TABLE IF EXISTS audit_logs')
    op.drop_index('ix_invitations_company_id', table_name='invitations')
    op.create_foreign_key(None, 'invitations', 'companies', ['company_id'], ['id'])
    op.drop_index('ix_users_company_id', table_name='users')
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index('ix_users_company_id', 'users', ['company_id'], unique=False)
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_index('ix_invitations_company_id', 'invitations', ['company_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('old_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    # ### end Alembic commands ###
