"""Add default_tax_rate to companies

Revision ID: 90a121e69a2e
Revises: d53275884ee8
Create Date: 2026-05-12 23:40:05.773607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a121e69a2e'
down_revision = 'd53275884ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enumerations',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('translation_key', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'key', 'company_id', name='uq_enum_type_key_company')
    )
    op.create_index(op.f('ix_enumerations_company_id'), 'enumerations', ['company_id'], unique=False)
    op.create_index(op.f('ix_enumerations_group_id'), 'enumerations', ['group_id'], unique=False)
    op.create_index(op.f('ix_enumerations_key'), 'enumerations', ['key'], unique=False)
    op.create_index(op.f('ix_enumerations_tenant_id'), 'enumerations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_enumerations_type'), 'enumerations', ['type'], unique=False)
    op.create_index('ix_enumerations_type_company_active', 'enumerations', ['type', 'company_id', 'is_active'], unique=False)
    op.create_table('inventory_locations',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Primary scan code. Format: PA-SEC-NV-POS (e.g. 01-05-02-A)'),
    sa.Column('aisle', sa.String(length=10), nullable=True, comment='Pasillo'),
    sa.Column('section', sa.String(length=10), nullable=True, comment='Columna/Bay'),
    sa.Column('level', sa.String(length=10), nullable=True, comment='Nivel/Shelf'),
    sa.Column('bin_slot', sa.String(length=10), nullable=True, comment='Gaveta/Bin'),
    sa.Column('zone_type', sa.String(length=20), nullable=False, comment='Functional zone: RECEIVING, STORAGE, PICKING, QUALITY, SHIPPING, TRANSIT'),
    sa.Column('storage_type', sa.String(length=20), nullable=False, comment='Environmental requirement: DRY, COLD, HAZMAT, LOCKED'),
    sa.Column('is_multisku', sa.Boolean(), nullable=False, comment='If False, only one SKU is allowed (e.g. medical/regulated items)'),
    sa.Column('velocity_code', sa.String(length=1), nullable=True, comment='A=High rotation (near shipping), B=Medium, C=Slow/Dead stock'),
    sa.Column('max_capacity_units', sa.Numeric(precision=15, scale=4), nullable=False, comment='Max units (pieces). 0 = unlimited.'),
    sa.Column('max_weight_kg', sa.Numeric(precision=15, scale=4), nullable=False, comment='Max weight in kg. 0 = unlimited. SAFETY-CRITICAL: no manager override.'),
    sa.Column('width_cm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('depth_cm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_units', sa.Numeric(precision=15, scale=4), nullable=False, comment='Current unit count. Denormalized cache — updated atomically.'),
    sa.Column('current_weight_kg', sa.Numeric(precision=15, scale=4), nullable=False, comment='Current weight in kg. Denormalized cache — updated atomically.'),
    sa.Column('is_virtual', sa.Boolean(), nullable=False, comment='True for system-managed zones: SYS_RECEIVING, SYS_TRANSIT, SYS_QUALITY'),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'warehouse_id', 'code', name='uq_location_per_warehouse')
    )
    op.create_index(op.f('ix_inventory_locations_code'), 'inventory_locations', ['code'], unique=False)
    op.create_index(op.f('ix_inventory_locations_company_id'), 'inventory_locations', ['company_id'], unique=False)
    op.create_index(op.f('ix_inventory_locations_group_id'), 'inventory_locations', ['group_id'], unique=False)
    op.create_index(op.f('ix_inventory_locations_tenant_id'), 'inventory_locations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_locations_warehouse_id'), 'inventory_locations', ['warehouse_id'], unique=False)
    op.create_table('security_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('collaborator_id', sa.UUID(), nullable=True),
    sa.Column('access_method', sa.String(length=50), nullable=False),
    sa.Column('identity_identifier', sa.String(length=255), nullable=False),
    sa.Column('roles_snapshot', sa.JSON(), nullable=True),
    sa.Column('scopes_snapshot', sa.JSON(), nullable=True),
    sa.Column('terminal_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_audit_logs_collaborator_id'), 'security_audit_logs', ['collaborator_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_company_id'), 'security_audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_user_id'), 'security_audit_logs', ['user_id'], unique=False)
    op.add_column('audit_logs', sa.Column('collaborator_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('external_contact_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_audit_logs_collaborator_id'), 'audit_logs', ['collaborator_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_external_contact_id'), 'audit_logs', ['external_contact_id'], unique=False)
    op.add_column('companies', sa.Column('default_tax_rate', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'default_tax_rate')
    op.drop_index(op.f('ix_audit_logs_external_contact_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_collaborator_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'external_contact_id')
    op.drop_column('audit_logs', 'collaborator_id')
    op.drop_index(op.f('ix_security_audit_logs_user_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_company_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_collaborator_id'), table_name='security_audit_logs')
    op.drop_table('security_audit_logs')
    op.drop_index(op.f('ix_inventory_locations_warehouse_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_tenant_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_group_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_company_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_code'), table_name='inventory_locations')
    op.drop_table('inventory_locations')
    op.drop_index('ix_enumerations_type_company_active', table_name='enumerations')
    op.drop_index(op.f('ix_enumerations_type'), table_name='enumerations')
    op.drop_index(op.f('ix_enumerations_tenant_id'), table_name='enumerations')
    op.drop_index(op.f('ix_enumerations_key'), table_name='enumerations')
    op.drop_index(op.f('ix_enumerations_group_id'), table_name='enumerations')
    op.drop_index(op.f('ix_enumerations_company_id'), table_name='enumerations')
    op.drop_table('enumerations')
    # ### end Alembic commands ###