"""add_rfid_identity_token

Revision ID: a2f2785f0cb6
Revises: 5902da5eece9
Create Date: 2026-03-10 16:13:47.266446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f2785f0cb6'
down_revision = '5902da5eece9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_metadata',
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('service_source', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_metadata_company_id'), 'file_metadata', ['company_id'], unique=False)
    op.create_index(op.f('ix_file_metadata_group_id'), 'file_metadata', ['group_id'], unique=False)
    op.create_index(op.f('ix_file_metadata_key'), 'file_metadata', ['key'], unique=False)
    op.add_column('permissions', sa.Column('slug', sa.String(length=100), nullable=False))
    op.add_column('permissions', sa.Column('module_name', sa.String(length=50), nullable=False))
    op.add_column('permissions', sa.Column('description', sa.String(length=255), nullable=True))
    op.alter_column('permissions', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'permissions', ['slug'])
    op.create_index(op.f('ix_user_company_roles_company_id'), 'user_company_roles', ['company_id'], unique=False)
    op.add_column('users', sa.Column('identity_token', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_identity_token'), 'users', ['identity_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_identity_token'), table_name='users')
    op.drop_column('users', 'identity_token')
    op.drop_index(op.f('ix_user_company_roles_company_id'), table_name='user_company_roles')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.alter_column('permissions', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('permissions', 'description')
    op.drop_column('permissions', 'module_name')
    op.drop_column('permissions', 'slug')
    op.drop_index(op.f('ix_file_metadata_key'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_group_id'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_company_id'), table_name='file_metadata')
    op.drop_table('file_metadata')
    # ### end Alembic commands ###