"""Sync AuditLog correlation_id

Revision ID: d67ab4f78380
Revises: b3e1f9d0a14c
Create Date: 2026-04-13 17:27:52.122883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd67ab4f78380'
down_revision = 'b3e1f9d0a14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('correlation_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('client_ip', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('audit_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audit_logs', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audit_logs', sa.Column('transaction_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('audit_logs', sa.Column('version_id', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('audit_logs', 'company_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='company_id::uuid')
    op.alter_column('audit_logs', 'group_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='group_id::uuid')
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('audit_logs', 'old_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_group_id'), 'audit_logs', ['group_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_column('audit_logs', 'trace_id')
    op.drop_column('audit_logs', 'ip_address')
    op.alter_column('file_metadata', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('invitations', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('permissions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('refresh_tokens_company_id_fkey', 'refresh_tokens', type_='foreignkey')
    op.alter_column('role_permissions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_company_roles', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_company_roles', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('role_permissions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key('refresh_tokens_company_id_fkey', 'refresh_tokens', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('permissions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('invitations', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('file_metadata', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('audit_logs', sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('trace_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_group_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('audit_logs', 'new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('audit_logs', 'group_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('audit_logs', 'version_id')
    op.drop_column('audit_logs', 'is_active')
    op.drop_column('audit_logs', 'transaction_id')
    op.drop_column('audit_logs', 'deleted_at')
    op.drop_column('audit_logs', 'updated_by')
    op.drop_column('audit_logs', 'created_by')
    op.drop_column('audit_logs', 'updated_at')
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('audit_logs', 'client_ip')
    op.drop_column('audit_logs', 'tenant_id')
    op.drop_column('audit_logs', 'correlation_id')
    # ### end Alembic commands ###