"""Add missing fields to Company

Revision ID: eb347eb48b7c
Revises: 4055593d8e6a
Create Date: 2026-03-24 16:57:22.079103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb347eb48b7c'
down_revision = '4055593d8e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('country_code', sa.String(length=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'country_code')
    # ### end Alembic commands ###
