"""Add refresh token families and rotation audit tables

Revision ID: f20a0170fc12
Revises: c7d4e5f6a8b9
Create Date: 2026-05-29 10:14:53.582075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f20a0170fc12'
down_revision = 'c7d4e5f6a8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_locations',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Primary scan code. Format: PA-SEC-NV-POS (e.g. 01-05-02-A)'),
    sa.Column('aisle', sa.String(length=10), nullable=True, comment='Pasillo'),
    sa.Column('section', sa.String(length=10), nullable=True, comment='Columna/Bay'),
    sa.Column('level', sa.String(length=10), nullable=True, comment='Nivel/Shelf'),
    sa.Column('bin_slot', sa.String(length=10), nullable=True, comment='Gaveta/Bin'),
    sa.Column('zone_type', sa.String(length=20), nullable=False, comment='Functional zone: RECEIVING, STORAGE, PICKING, QUALITY, SHIPPING, TRANSIT'),
    sa.Column('storage_type', sa.String(length=20), nullable=False, comment='Environmental requirement: DRY, COLD, HAZMAT, LOCKED'),
    sa.Column('is_multisku', sa.Boolean(), nullable=False, comment='If False, only one SKU is allowed (e.g. medical/regulated items)'),
    sa.Column('velocity_code', sa.String(length=1), nullable=True, comment='A=High rotation (near shipping), B=Medium, C=Slow/Dead stock'),
    sa.Column('max_capacity_units', sa.Numeric(precision=15, scale=4), nullable=False, comment='Max units (pieces). 0 = unlimited.'),
    sa.Column('max_weight_kg', sa.Numeric(precision=15, scale=4), nullable=False, comment='Max weight in kg. 0 = unlimited. SAFETY-CRITICAL: no manager override.'),
    sa.Column('width_cm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('depth_cm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_units', sa.Numeric(precision=15, scale=4), nullable=False, comment='Current unit count. Denormalized cache — updated atomically.'),
    sa.Column('current_weight_kg', sa.Numeric(precision=15, scale=4), nullable=False, comment='Current weight in kg. Denormalized cache — updated atomically.'),
    sa.Column('is_virtual', sa.Boolean(), nullable=False, comment='True for system-managed zones: SYS_RECEIVING, SYS_TRANSIT, SYS_QUALITY'),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'warehouse_id', 'code', name='uq_location_per_warehouse')
    )
    op.create_index(op.f('ix_inventory_locations_code'), 'inventory_locations', ['code'], unique=False)
    op.create_index(op.f('ix_inventory_locations_company_id'), 'inventory_locations', ['company_id'], unique=False)
    op.create_index(op.f('ix_inventory_locations_group_id'), 'inventory_locations', ['group_id'], unique=False)
    op.create_index(op.f('ix_inventory_locations_tenant_id'), 'inventory_locations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_locations_warehouse_id'), 'inventory_locations', ['warehouse_id'], unique=False)
    op.create_table('refresh_token_families',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_salt', sa.String(length=64), nullable=False),
    sa.Column('current_generation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=255), nullable=True),
    sa.Column('last_refresh_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('last_refresh_jti', sa.UUID(), nullable=True),
    sa.Column('refresh_window_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_salt')
    )
    op.create_index('idx_refresh_window', 'refresh_token_families', ['refresh_window_expires_at'], unique=False)
    op.create_index('idx_revoked_families', 'refresh_token_families', ['revoked_at'], unique=False)
    op.create_index('idx_user_company_family', 'refresh_token_families', ['user_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_families_company_id'), 'refresh_token_families', ['company_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_families_group_id'), 'refresh_token_families', ['group_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_families_id'), 'refresh_token_families', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_token_families_refresh_window_expires_at'), 'refresh_token_families', ['refresh_window_expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_families_revoked_at'), 'refresh_token_families', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_families_tenant_id'), 'refresh_token_families', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_families_user_id'), 'refresh_token_families', ['user_id'], unique=False)
    op.create_table('refresh_token_rotation_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_generation', sa.Integer(), nullable=True),
    sa.Column('new_generation', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('concurrent_attempt_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('failover_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['refresh_token_families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_family_audit_timeline', 'refresh_token_rotation_audit', ['family_id', 'created_at'], unique=False)
    op.create_index('idx_reuse_detection', 'refresh_token_rotation_audit', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_rotation_audit_action'), 'refresh_token_rotation_audit', ['action'], unique=False)
    op.create_index(op.f('ix_refresh_token_rotation_audit_company_id'), 'refresh_token_rotation_audit', ['company_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_rotation_audit_family_id'), 'refresh_token_rotation_audit', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_rotation_audit_group_id'), 'refresh_token_rotation_audit', ['group_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_rotation_audit_id'), 'refresh_token_rotation_audit', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_token_rotation_audit_tenant_id'), 'refresh_token_rotation_audit', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_rotation_audit_user_id'), 'refresh_token_rotation_audit', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_collaborator_id'), 'audit_logs', ['collaborator_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_external_contact_id'), 'audit_logs', ['external_contact_id'], unique=False)
    op.alter_column('companies', 'default_tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False,
               existing_server_default=sa.text('0.16'))
    op.create_index(op.f('ix_enumerations_group_id'), 'enumerations', ['group_id'], unique=False)
    op.alter_column('external_contacts', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('external_contacts', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('external_contacts', 'phone',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('external_contacts', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('external_contacts', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_external_contacts_company_id'), 'external_contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_external_contacts_group_id'), 'external_contacts', ['group_id'], unique=False)
    op.create_index(op.f('ix_external_contacts_tenant_id'), 'external_contacts', ['tenant_id'], unique=False)
    op.alter_column('security_audit_logs', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('security_audit_logs', 'access_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('security_audit_logs', 'identity_identifier',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('security_audit_logs', 'roles_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('security_audit_logs', 'scopes_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('security_audit_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.create_index(op.f('ix_security_audit_logs_collaborator_id'), 'security_audit_logs', ['collaborator_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_company_id'), 'security_audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_user_id'), 'security_audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_audit_logs_user_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_company_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_collaborator_id'), table_name='security_audit_logs')
    op.alter_column('security_audit_logs', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('security_audit_logs', 'scopes_snapshot',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('security_audit_logs', 'roles_snapshot',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('security_audit_logs', 'identity_identifier',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('security_audit_logs', 'access_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('security_audit_logs', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_external_contacts_tenant_id'), table_name='external_contacts')
    op.drop_index(op.f('ix_external_contacts_group_id'), table_name='external_contacts')
    op.drop_index(op.f('ix_external_contacts_company_id'), table_name='external_contacts')
    op.alter_column('external_contacts', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('external_contacts', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('external_contacts', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('external_contacts', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('external_contacts', 'full_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_enumerations_group_id'), table_name='enumerations')
    op.alter_column('companies', 'default_tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True,
               existing_server_default=sa.text('0.16'))
    op.drop_index(op.f('ix_audit_logs_external_contact_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_collaborator_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_refresh_token_rotation_audit_user_id'), table_name='refresh_token_rotation_audit')
    op.drop_index(op.f('ix_refresh_token_rotation_audit_tenant_id'), table_name='refresh_token_rotation_audit')
    op.drop_index(op.f('ix_refresh_token_rotation_audit_id'), table_name='refresh_token_rotation_audit')
    op.drop_index(op.f('ix_refresh_token_rotation_audit_group_id'), table_name='refresh_token_rotation_audit')
    op.drop_index(op.f('ix_refresh_token_rotation_audit_family_id'), table_name='refresh_token_rotation_audit')
    op.drop_index(op.f('ix_refresh_token_rotation_audit_company_id'), table_name='refresh_token_rotation_audit')
    op.drop_index(op.f('ix_refresh_token_rotation_audit_action'), table_name='refresh_token_rotation_audit')
    op.drop_index('idx_reuse_detection', table_name='refresh_token_rotation_audit')
    op.drop_index('idx_family_audit_timeline', table_name='refresh_token_rotation_audit')
    op.drop_table('refresh_token_rotation_audit')
    op.drop_index(op.f('ix_refresh_token_families_user_id'), table_name='refresh_token_families')
    op.drop_index(op.f('ix_refresh_token_families_tenant_id'), table_name='refresh_token_families')
    op.drop_index(op.f('ix_refresh_token_families_revoked_at'), table_name='refresh_token_families')
    op.drop_index(op.f('ix_refresh_token_families_refresh_window_expires_at'), table_name='refresh_token_families')
    op.drop_index(op.f('ix_refresh_token_families_id'), table_name='refresh_token_families')
    op.drop_index(op.f('ix_refresh_token_families_group_id'), table_name='refresh_token_families')
    op.drop_index(op.f('ix_refresh_token_families_company_id'), table_name='refresh_token_families')
    op.drop_index('idx_user_company_family', table_name='refresh_token_families')
    op.drop_index('idx_revoked_families', table_name='refresh_token_families')
    op.drop_index('idx_refresh_window', table_name='refresh_token_families')
    op.drop_table('refresh_token_families')
    op.drop_index(op.f('ix_inventory_locations_warehouse_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_tenant_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_group_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_company_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_code'), table_name='inventory_locations')
    op.drop_table('inventory_locations')
    # ### end Alembic commands ###