"""Add PriceAgreement and link to ProductPrice

Revision ID: 43a7412121f6
Revises: a1b2c3d4e5f6
Create Date: 2026-04-14 22:09:48.370844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43a7412121f6'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Enums are handled with manual guards because named Enums in sa.Column try to create types without IF NOT EXISTS
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'agreementtype') THEN CREATE TYPE agreementtype AS ENUM ('CONTRACT', 'DISCOUNT_LIST', 'GLOBAL'); END IF; END $$;")


    op.create_table('price_agreements',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agreement_type', postgresql.ENUM('CONTRACT', 'DISCOUNT_LIST', 'GLOBAL', name='agreementtype', create_type=False), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('external_code', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('review_status', sa.String(length=50), server_default='APPROVED', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_agreements_company_id'), 'price_agreements', ['company_id'], unique=False)
    op.create_index(op.f('ix_price_agreements_customer_id'), 'price_agreements', ['customer_id'], unique=False)
    op.create_index(op.f('ix_price_agreements_group_id'), 'price_agreements', ['group_id'], unique=False)
    op.create_index(op.f('ix_price_agreements_tenant_id'), 'price_agreements', ['tenant_id'], unique=False)
    op.drop_index('ix_items_code', table_name='items')
    op.drop_index('ix_items_company_id', table_name='items')
    op.drop_index('ix_items_group_id', table_name='items')
    op.drop_index('ix_items_sku', table_name='items')
    op.drop_table('items')
    op.add_column('audit_logs', sa.Column('correlation_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('client_ip', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('audit_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audit_logs', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audit_logs', sa.Column('transaction_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('audit_logs', sa.Column('version_id', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('audit_logs', 'company_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using="company_id::uuid")
    op.alter_column('audit_logs', 'group_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using="group_id::uuid")
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('audit_logs', 'old_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using="id::uuid")
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_group_id'), 'audit_logs', ['group_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'trace_id')
    op.alter_column('concepts', 'concept_type',
               existing_type=postgresql.ENUM('ENTRY', 'OUTPUT', 'ADJUSTMENT', 'TRANSFER', name='concepttype'),
               type_=sa.Enum('ENTRY', 'OUTPUT', 'TRANSFER', 'ADJUSTMENT', name='movementtype'),
               comment=None,
               existing_comment='Direction of movement: Entry, Output, or Adjustment',
               existing_nullable=False,
               postgresql_using="concept_type::text::movementtype")
    op.alter_column('concepts', 'code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               comment=None,
               existing_comment="Short code for folio generation (e.g., 'ENT', 'SAL', 'AJU')",
               existing_nullable=False)
    op.alter_column('concepts', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               comment=None,
               existing_comment="Display name (e.g., 'Entrada de Compra', 'Salida por Venta')",
               existing_nullable=False)
    op.alter_column('concepts', 'description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               comment=None,
               existing_comment='Detailed description of when to use this concept',
               existing_nullable=True)
    op.drop_index('ix_concepts_concept_type', table_name='concepts')
    op.create_index(op.f('ix_concepts_tenant_id'), 'concepts', ['tenant_id'], unique=False)
    op.drop_column('concepts', 'type')
    op.create_index(op.f('ix_document_series_tenant_id'), 'document_series', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_file_metadata_tenant_id'), 'file_metadata', ['tenant_id'], unique=False)
    op.drop_column('idempotency_keys', 'created_at')
    op.drop_column('idempotency_keys', 'user_id')
    op.create_index(op.f('ix_inventory_documents_tenant_id'), 'inventory_documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_tenant_id'), 'inventory_movements', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_tenant_id'), 'inventory_snapshots', ['tenant_id'], unique=False)
    op.add_column('locations', sa.Column('parent_location_id', sa.UUID(), nullable=True))
    op.add_column('locations', sa.Column('max_capacity', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('locations', sa.Column('current_capacity', sa.Numeric(precision=18, scale=4), nullable=True))
    op.create_index(op.f('ix_locations_parent_location_id'), 'locations', ['parent_location_id'], unique=False)
    op.create_index(op.f('ix_locations_tenant_id'), 'locations', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'locations', 'locations', ['parent_location_id'], ['id'])
    op.add_column('product_prices', sa.Column('agreement_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_product_prices_agreement_id'), 'product_prices', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_product_prices_tenant_id'), 'product_prices', ['tenant_id'], unique=False)
    op.add_column('products', sa.Column('stock_quantity', sa.Numeric(precision=18, scale=4), nullable=False))
    op.add_column('products', sa.Column('bin_location', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('master_product_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('sku', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'DISCONTINUED', name='productstatus'), nullable=False))
    op.add_column('products', sa.Column('sat_product_code', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('uq_product_company_code', 'products', type_='unique')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_item_company_sku', 'products', ['company_id', 'sku'])
    op.drop_column('products', 'revision')
    op.drop_column('products', 'height')
    op.drop_column('products', 'order_multiple')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'reorder_point')
    op.drop_column('products', 'active')
    op.drop_column('products', 'width')
    op.drop_column('products', 'safety_stock')
    op.drop_column('products', 'min_order_qty')
    op.drop_column('products', 'length')
    op.drop_column('products', 'alias')
    op.drop_column('products', 'max_order_qty')
    op.drop_column('products', 'unit_code')
    op.create_index(op.f('ix_sales_orders_tenant_id'), 'sales_orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_warehouse_groups_tenant_id'), 'warehouse_groups', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_warehouse_types_tenant_id'), 'warehouse_types', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_warehouse_zones_tenant_id'), 'warehouse_zones', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_warehouses_tenant_id'), 'warehouses', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_tenant_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouse_zones_tenant_id'), table_name='warehouse_zones')
    op.drop_index(op.f('ix_warehouse_types_tenant_id'), table_name='warehouse_types')
    op.drop_index(op.f('ix_warehouse_groups_tenant_id'), table_name='warehouse_groups')
    op.drop_index(op.f('ix_sales_orders_tenant_id'), table_name='sales_orders')
    op.add_column('products', sa.Column('unit_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('max_order_qty', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('alias', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('length', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('min_order_qty', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('safety_stock', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('width', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('reorder_point', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('weight', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('order_multiple', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('height', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('revision', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint('uq_item_company_sku', 'products', type_='unique')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_unique_constraint('uq_product_company_code', 'products', ['company_id', 'code'])
    op.alter_column('products', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('products', 'tenant_id')
    op.drop_column('products', 'sat_product_code')
    op.drop_column('products', 'status')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'master_product_id')
    op.drop_column('products', 'bin_location')
    op.drop_column('products', 'stock_quantity')
    op.drop_index(op.f('ix_product_prices_tenant_id'), table_name='product_prices')
    op.drop_index(op.f('ix_product_prices_agreement_id'), table_name='product_prices')
    op.drop_column('product_prices', 'agreement_id')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_index(op.f('ix_locations_tenant_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_parent_location_id'), table_name='locations')
    op.drop_column('locations', 'current_capacity')
    op.drop_column('locations', 'max_capacity')
    op.drop_column('locations', 'parent_location_id')
    op.drop_index(op.f('ix_inventory_snapshots_tenant_id'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_movements_tenant_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_documents_tenant_id'), table_name='inventory_documents')
    op.add_column('idempotency_keys', sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('idempotency_keys', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_file_metadata_tenant_id'), table_name='file_metadata')
    op.drop_index(op.f('ix_document_series_tenant_id'), table_name='document_series')
    op.add_column('concepts', sa.Column('type', postgresql.ENUM('ENTRY', 'OUTPUT', 'TRANSFER', 'ADJUSTMENT', name='movementtype'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_concepts_tenant_id'), table_name='concepts')
    op.create_index('ix_concepts_concept_type', 'concepts', ['concept_type'], unique=False)
    op.alter_column('concepts', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               comment='Detailed description of when to use this concept',
               existing_nullable=True)
    op.alter_column('concepts', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               comment="Display name (e.g., 'Entrada de Compra', 'Salida por Venta')",
               existing_nullable=False)
    op.alter_column('concepts', 'code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               comment="Short code for folio generation (e.g., 'ENT', 'SAL', 'AJU')",
               existing_nullable=False)
    op.alter_column('concepts', 'concept_type',
               existing_type=sa.Enum('ENTRY', 'OUTPUT', 'TRANSFER', 'ADJUSTMENT', name='movementtype'),
               type_=postgresql.ENUM('ENTRY', 'OUTPUT', 'ADJUSTMENT', 'TRANSFER', name='concepttype'),
               comment='Direction of movement: Entry, Output, or Adjustment',
               existing_nullable=False)
    op.add_column('audit_logs', sa.Column('trace_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_group_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('audit_logs', 'new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('audit_logs', 'group_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('audit_logs', 'version_id')
    op.drop_column('audit_logs', 'is_active')
    op.drop_column('audit_logs', 'transaction_id')
    op.drop_column('audit_logs', 'deleted_at')
    op.drop_column('audit_logs', 'updated_by')
    op.drop_column('audit_logs', 'created_by')
    op.drop_column('audit_logs', 'updated_at')
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('audit_logs', 'client_ip')
    op.drop_column('audit_logs', 'tenant_id')
    op.drop_column('audit_logs', 'correlation_id')
    op.create_table('items',
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('stock_quantity', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('bin_location', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'ACTIVE', 'INACTIVE', 'DISCONTINUED', name='productstatus'), server_default=sa.text("'ACTIVE'::productstatus"), autoincrement=False, nullable=False),
    sa.Column('master_product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sat_product_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='items_pkey'),
    sa.UniqueConstraint('company_id', 'code', name='uq_item_company_code')
    )
    op.create_index('ix_items_sku', 'items', ['sku'], unique=False)
    op.create_index('ix_items_group_id', 'items', ['group_id'], unique=False)
    op.create_index('ix_items_company_id', 'items', ['company_id'], unique=False)
    op.create_index('ix_items_code', 'items', ['code'], unique=False)
    op.drop_index(op.f('ix_price_agreements_tenant_id'), table_name='price_agreements')
    op.drop_index(op.f('ix_price_agreements_group_id'), table_name='price_agreements')
    op.drop_index(op.f('ix_price_agreements_customer_id'), table_name='price_agreements')
    op.drop_index(op.f('ix_price_agreements_company_id'), table_name='price_agreements')
    op.drop_table('price_agreements')
    # ### end Alembic commands ###
