"""001_wms_initial_fixed

Revision ID: 443227c8fefd
Revises: 
Create Date: 2026-02-24 18:39:28.986331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443227c8fefd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concepts',
    sa.Column('code', sa.String(length=10), nullable=False, comment="Short code for folio generation (e.g., 'ENT', 'SAL', 'AJU')"),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Display name (e.g., 'Entrada de Compra', 'Salida por Venta')"),
    sa.Column('description', sa.String(length=250), nullable=True, comment='Detailed description of when to use this concept'),
    sa.Column('concept_type', sa.Enum('ENTRY', 'OUTPUT', 'ADJUSTMENT', name='concepttype'), nullable=False, comment='Direction of movement: Entry, Output, or Adjustment'),
    sa.Column('affect_stock', sa.Boolean(), nullable=False, comment='If True, movements with this concept will update InventorySnapshot'),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_concept_tenant_code', 'concepts', ['company_id', 'code'], unique=True)
    op.create_index(op.f('ix_concepts_code'), 'concepts', ['code'], unique=False)
    op.create_index(op.f('ix_concepts_company_id'), 'concepts', ['company_id'], unique=False)
    op.create_index(op.f('ix_concepts_concept_type'), 'concepts', ['concept_type'], unique=False)
    op.create_table('document_series',
    sa.Column('concept_code', sa.String(length=10), nullable=False, comment="Reference to Concept.code (e.g., 'ENT', 'SAL', 'AJU')"),
    sa.Column('prefix', sa.String(length=20), nullable=False, comment="Custom prefix defined by tenant (e.g., 'ALM-A', 'INV-', 'ENT')"),
    sa.Column('current_number', sa.Integer(), nullable=False, comment='Last used number in the sequence. Incremented atomically.'),
    sa.Column('year_reset', sa.Integer(), nullable=True, comment='Optional: Year for resetting sequence (e.g., 2026). If set, sequence resets each year.'),
    sa.Column('separator', sa.String(length=5), nullable=False, comment="Separator character between prefix, year, and number (e.g., '-', '/', '_')"),
    sa.Column('padding', sa.Integer(), nullable=False, comment='Number of digits for zero-padding (e.g., 5 → 00001, 3 → 001)'),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_series_company_id'), 'document_series', ['company_id'], unique=False)
    op.create_index(op.f('ix_document_series_concept_code'), 'document_series', ['concept_code'], unique=False)
    op.create_index('ix_series_tenant_concept', 'document_series', ['company_id', 'concept_code'], unique=True)
    op.create_table('products',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('revision', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('safety_stock', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('min_order_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('max_order_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('order_multiple', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('weight', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('length', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('width', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('height', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_code', sa.String(length=10), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_product_company_code')
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=False)
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_table('warehouse_groups',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_groups_company_id'), 'warehouse_groups', ['company_id'], unique=False)
    op.create_table('warehouse_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_types_company_id'), 'warehouse_types', ['company_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('capacity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_code', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('warehouse_type_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_group_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_group_id'], ['warehouse_groups.id'], ),
    sa.ForeignKeyConstraint(['warehouse_type_id'], ['warehouse_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_warehouse_company_code')
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=False)
    op.create_index(op.f('ix_warehouses_company_id'), 'warehouses', ['company_id'], unique=False)
    op.create_table('inventory_documents',
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'CANCELLED', name='documentstatus'), nullable=False),
    sa.Column('observations', sa.String(length=1000), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('sub_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'sequence_number', name='uq_document_company_sequence')
    )
    op.create_index(op.f('ix_inventory_documents_company_id'), 'inventory_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_inventory_documents_folio'), 'inventory_documents', ['folio'], unique=False)
    op.create_index(op.f('ix_inventory_documents_sequence_number'), 'inventory_documents', ['sequence_number'], unique=False)
    op.create_index(op.f('ix_inventory_documents_warehouse_id'), 'inventory_documents', ['warehouse_id'], unique=False)
    op.create_table('inventory_snapshots',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'product_id', 'warehouse_id', name='uq_snapshot_company_product_warehouse')
    )
    op.create_index(op.f('ix_inventory_snapshots_company_id'), 'inventory_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_product_id'), 'inventory_snapshots', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_warehouse_id'), 'inventory_snapshots', ['warehouse_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('sequence_number', sa.Integer(), nullable=False, comment='Número secuencial de línea dentro del documento'),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='Cantidad movida (soporta hasta 4 decimales)'),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('affected_stock', sa.Boolean(), nullable=False, comment='Indica si este movimiento debe impactar el stock actual'),
    sa.Column('purchase_price', sa.Numeric(precision=18, scale=4), nullable=False, comment='Costo unitario de compra al momento del movimiento'),
    sa.Column('sell_price', sa.Numeric(precision=18, scale=4), nullable=False, comment='Precio unitario de venta'),
    sa.Column('total_line', sa.Numeric(precision=18, scale=4), nullable=False, comment='Total de la línea (quantity * price)'),
    sa.Column('transaction_id', sa.String(length=36), nullable=True, comment='ID de transacción para trazabilidad cruzada'),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['inventory_documents.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_company_id'), 'inventory_movements', ['company_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_document_id'), 'inventory_movements', ['document_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_lot_number'), 'inventory_movements', ['lot_number'], unique=False)
    op.create_index(op.f('ix_inventory_movements_product_id'), 'inventory_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_transaction_id'), 'inventory_movements', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_warehouse_id'), 'inventory_movements', ['warehouse_id'], unique=False)
    op.create_index('ix_mov_doc_sequence', 'inventory_movements', ['document_id', 'sequence_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mov_doc_sequence', table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_warehouse_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_transaction_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_product_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_lot_number'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_document_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_company_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_inventory_snapshots_warehouse_id'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_product_id'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_company_id'), table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    op.drop_index(op.f('ix_inventory_documents_warehouse_id'), table_name='inventory_documents')
    op.drop_index(op.f('ix_inventory_documents_sequence_number'), table_name='inventory_documents')
    op.drop_index(op.f('ix_inventory_documents_folio'), table_name='inventory_documents')
    op.drop_index(op.f('ix_inventory_documents_company_id'), table_name='inventory_documents')
    op.drop_table('inventory_documents')
    op.drop_index(op.f('ix_warehouses_company_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_warehouse_types_company_id'), table_name='warehouse_types')
    op.drop_table('warehouse_types')
    op.drop_index(op.f('ix_warehouse_groups_company_id'), table_name='warehouse_groups')
    op.drop_table('warehouse_groups')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_series_tenant_concept', table_name='document_series')
    op.drop_index(op.f('ix_document_series_concept_code'), table_name='document_series')
    op.drop_index(op.f('ix_document_series_company_id'), table_name='document_series')
    op.drop_table('document_series')
    op.drop_index(op.f('ix_concepts_concept_type'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_company_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_code'), table_name='concepts')
    op.drop_index('ix_concept_tenant_code', table_name='concepts')
    op.drop_table('concepts')
    op.drop_table('companies')
    # ### end Alembic commands ###
