"""wms_pricing_audit

Revision ID: 9a4d4173b906
Revises: 66b0613be198
Create Date: 2026-03-09 17:07:35.445915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a4d4173b906'
down_revision: Union[str, None] = '66b0613be198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('location_id', sa.UUID(), nullable=True, comment='ID de la ubicación física (Bin) en el WMS'))
    op.create_index(op.f('ix_inventory_movements_location_id'), 'inventory_movements', ['location_id'], unique=False)
    op.create_foreign_key(None, 'inventory_movements', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(None, 'inventory_movements', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'inventory_snapshots', 'products', ['product_id'], ['id'])
    op.add_column('product_prices', sa.Column('amount', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False))
    op.add_column('product_prices', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('product_prices', sa.Column('change_reason', sa.String(length=255), nullable=False))
    op.drop_column('product_prices', 'effective_date')
    op.drop_column('product_prices', 'standard_cost')
    op.drop_column('product_prices', 'labor_cost')
    op.drop_column('product_prices', 'sale_price')
    op.drop_column('product_prices', 'indirect_cost')
    op.drop_column('product_prices', 'purchase_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_prices', sa.Column('purchase_price', sa.NUMERIC(precision=15, scale=4), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('product_prices', sa.Column('indirect_cost', sa.NUMERIC(precision=15, scale=4), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('product_prices', sa.Column('sale_price', sa.NUMERIC(precision=15, scale=4), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('product_prices', sa.Column('labor_cost', sa.NUMERIC(precision=15, scale=4), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('product_prices', sa.Column('standard_cost', sa.NUMERIC(precision=15, scale=4), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('product_prices', sa.Column('effective_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('product_prices', 'change_reason')
    op.drop_column('product_prices', 'version')
    op.drop_column('product_prices', 'amount')
    op.drop_constraint(None, 'inventory_snapshots', type_='foreignkey')
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_movements_location_id'), table_name='inventory_movements')
    op.drop_column('inventory_movements', 'location_id')
    # ### end Alembic commands ###
