"""Add_Money_VO_and_Locations_to_WMS

Revision ID: f106f9659684
Revises: 66b0613be198
Create Date: 2026-03-21 10:57:42.141212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f106f9659684'
down_revision: Union[str, None] = '66b0613be198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_metadata',
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('service_source', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_metadata_company_id'), 'file_metadata', ['company_id'], unique=False)
    op.create_index(op.f('ix_file_metadata_group_id'), 'file_metadata', ['group_id'], unique=False)
    op.create_index(op.f('ix_file_metadata_key'), 'file_metadata', ['key'], unique=False)
    op.create_table('items',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('stock_quantity', sa.Float(), nullable=False),
    sa.Column('bin_location', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_item_company_code')
    )
    op.create_index(op.f('ix_items_code'), 'items', ['code'], unique=False)
    op.create_index(op.f('ix_items_company_id'), 'items', ['company_id'], unique=False)
    op.create_index(op.f('ix_items_group_id'), 'items', ['group_id'], unique=False)
    op.create_index(op.f('ix_items_sku'), 'items', ['sku'], unique=False)
    op.create_table('locations',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('zone_code', sa.String(length=50), nullable=False),
    sa.Column('bin_code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('type', sa.Enum('RECEIVING', 'PICKING', 'OVERSTOCK', name='locationtype'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'warehouse_id', 'zone_code', 'bin_code', name='uq_location_coords')
    )
    op.create_index(op.f('ix_locations_company_id'), 'locations', ['company_id'], unique=False)
    op.create_index(op.f('ix_locations_group_id'), 'locations', ['group_id'], unique=False)
    op.create_index(op.f('ix_locations_warehouse_id'), 'locations', ['warehouse_id'], unique=False)
    op.create_table('warehouse_zones',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'warehouse_id', 'code', name='uq_zone_warehouse_code')
    )
    op.create_index(op.f('ix_warehouse_zones_code'), 'warehouse_zones', ['code'], unique=False)
    op.create_index(op.f('ix_warehouse_zones_company_id'), 'warehouse_zones', ['company_id'], unique=False)
    op.create_index(op.f('ix_warehouse_zones_group_id'), 'warehouse_zones', ['group_id'], unique=False)
    op.add_column('companies', sa.Column('base_currency', sa.String(length=3), nullable=False))
    # --- Refactor Inventory Movements (Data Preservation) ---
    op.alter_column('inventory_movements', 'purchase_price', new_column_name='_purchase_amount')
    op.add_column('inventory_movements', sa.Column('_purchase_currency', sa.String(length=3), server_default='USD', nullable=False))
    
    op.alter_column('inventory_movements', 'sell_price', new_column_name='_sell_amount')
    op.add_column('inventory_movements', sa.Column('_sell_currency', sa.String(length=3), server_default='USD', nullable=False))
    
    op.alter_column('inventory_movements', 'total_line', new_column_name='_total_amount')
    # total_line mapping doesn't have an original currency, so we add it with default
    op.add_column('inventory_movements', sa.Column('_total_currency', sa.String(length=3), server_default='USD', nullable=False))
    
    op.add_column('inventory_movements', sa.Column('location_id', sa.UUID(), nullable=True, comment='ID de la ubicación física (Bin) en el WMS'))
    op.create_index(op.f('ix_inventory_movements_location_id'), 'inventory_movements', ['location_id'], unique=False)
    op.create_foreign_key(None, 'inventory_movements', 'locations', ['location_id'], ['id'])

    # --- Refactor Product Prices (Data Preservation) ---
    # Baseline (66b0) has 'purchase_price' and 'currency_code', NOT 'amount'
    op.alter_column('product_prices', 'purchase_price', new_column_name='_amount')
    op.alter_column('product_prices', 'currency_code', new_column_name='_currency')
    
    op.add_column('product_prices', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('product_prices', sa.Column('change_reason', sa.String(length=255), server_default='Migration to Money VO', nullable=False))
    
    op.drop_column('product_prices', 'sale_price')
    op.drop_column('product_prices', 'standard_cost')
    op.drop_column('product_prices', 'labor_cost')
    op.drop_column('product_prices', 'indirect_cost')
    op.drop_column('product_prices', 'effective_date')
    op.drop_constraint(op.f('product_prices_warehouse_id_fkey'), 'product_prices', type_='foreignkey')
    op.drop_constraint(op.f('product_prices_product_id_fkey'), 'product_prices', type_='foreignkey')
    op.drop_constraint(op.f('sales_orders_folio_key'), 'sales_orders', type_='unique')
    op.create_index(op.f('ix_sales_orders_company_id'), 'sales_orders', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_group_id'), 'sales_orders', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_orders_group_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_company_id'), table_name='sales_orders')
    op.create_unique_constraint(op.f('sales_orders_folio_key'), 'sales_orders', ['folio'], postgresql_nulls_not_distinct=False)
    op.add_column('product_prices', sa.Column('labor_cost', sa.NUMERIC(precision=15, scale=4), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('product_prices', sa.Column('currency_code', sa.VARCHAR(length=3), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False))
    op.add_column('product_prices', sa.Column('sale_price', sa.NUMERIC(precision=15, scale=4), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('product_prices', sa.Column('purchase_price', sa.NUMERIC(precision=15, scale=4), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('product_prices', sa.Column('indirect_cost', sa.NUMERIC(precision=15, scale=4), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('product_prices', sa.Column('standard_cost', sa.NUMERIC(precision=15, scale=4), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('product_prices', sa.Column('effective_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('product_prices_product_id_fkey'), 'product_prices', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('product_prices_warehouse_id_fkey'), 'product_prices', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_column('product_prices', 'change_reason')
    op.drop_column('product_prices', 'version')
    op.drop_column('product_prices', '_currency')
    op.drop_column('product_prices', '_amount')
    op.add_column('inventory_movements', sa.Column('sell_price', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False, comment='Precio unitario de venta'))
    op.add_column('inventory_movements', sa.Column('total_line', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False, comment='Total de la línea (quantity * price)'))
    op.add_column('inventory_movements', sa.Column('purchase_price', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False, comment='Costo unitario de compra al momento del movimiento'))
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_movements_location_id'), table_name='inventory_movements')
    op.drop_column('inventory_movements', '_total_currency')
    op.drop_column('inventory_movements', '_total_amount')
    op.drop_column('inventory_movements', '_sell_currency')
    op.drop_column('inventory_movements', '_sell_amount')
    op.drop_column('inventory_movements', '_purchase_currency')
    op.drop_column('inventory_movements', '_purchase_amount')
    op.drop_column('inventory_movements', 'location_id')
    op.drop_column('companies', 'base_currency')
    op.drop_index(op.f('ix_warehouse_zones_group_id'), table_name='warehouse_zones')
    op.drop_index(op.f('ix_warehouse_zones_company_id'), table_name='warehouse_zones')
    op.drop_index(op.f('ix_warehouse_zones_code'), table_name='warehouse_zones')
    op.drop_table('warehouse_zones')
    op.drop_index(op.f('ix_locations_warehouse_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_group_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_company_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_items_sku'), table_name='items')
    op.drop_index(op.f('ix_items_group_id'), table_name='items')
    op.drop_index(op.f('ix_items_company_id'), table_name='items')
    op.drop_index(op.f('ix_items_code'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_file_metadata_key'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_group_id'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_company_id'), table_name='file_metadata')
    op.drop_table('file_metadata')
    # ### end Alembic commands ###
