// <auto-generated />
using System;
using Interno.Production.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Interno.Production.Migrations
{
    [DbContext(typeof(ProductionContext))]
    partial class ProductionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Interno.Domain.Catalog.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("AddressLine2")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.BloodType", b =>
                {
                    b.Property<string>("Group")
                        .HasColumnType("varchar(3) CHARACTER SET utf8mb4")
                        .HasMaxLength(3);

                    b.Property<string>("Donate")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Receive")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Group");

                    b.ToTable("BloodType");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BussinesName")
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.Property<int?>("BussinesPhoneId")
                        .HasColumnType("int");

                    b.Property<string>("BussinessType")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<string>("Observations")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("PrivacyPolicy")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Web")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("BussinesPhoneId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BusinessName")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<string>("JobTitle")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Manager")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PersonId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LicenseName")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Number")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("License");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.Mail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("PersonId");

                    b.ToTable("Mail");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AboutMe")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Birthplace")
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.Property<string>("BloodTypeGroup")
                        .HasColumnType("varchar(3) CHARACTER SET utf8mb4");

                    b.Property<string>("CURP")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<int>("Childrens")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("GlobalEntry")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("Height")
                        .HasColumnType("float");

                    b.Property<string>("LastNameMat")
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.Property<string>("LastNamePat")
                        .IsRequired()
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.Property<string>("MiddleName")
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.Property<string>("Nationality")
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.Property<bool>("Passport")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PrettyName")
                        .HasColumnType("varchar(150) CHARACTER SET utf8mb4")
                        .HasMaxLength(150);

                    b.Property<string>("RFC")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<int>("RelationshipStatus")
                        .HasColumnType("int");

                    b.Property<string>("Religion")
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.Property<bool>("Relocation")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SSN")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<bool>("Sentry")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Suspended")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TravelAvailability")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Visa")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BloodTypeGroup");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneExtension")
                        .HasColumnType("varchar(13) CHARACTER SET utf8mb4")
                        .HasMaxLength(13);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(13) CHARACTER SET utf8mb4")
                        .HasMaxLength(13);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("PersonId");

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.UM", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(4) CHARACTER SET utf8mb4")
                        .HasMaxLength(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<string>("Plural")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("Code");

                    b.ToTable("UM");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.ToTable("Area");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Area");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.Autority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.ToTable("Autority");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.Break", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BreakGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(15) CHARACTER SET utf8mb4")
                        .HasMaxLength(15);

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time(6)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreakGroupId");

                    b.HasIndex("TypeId");

                    b.ToTable("Break");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.BreakType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.ToTable("BreakType");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.BreaksGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("breaksGroups");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.BusinessUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.ToTable("BusinessUnit");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.JobPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("AutorityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Objetive")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("SalaryRangeFrom")
                        .HasColumnType("double");

                    b.Property<double>("SalaryRangeOut")
                        .HasColumnType("double");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AutorityId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("JobPosition");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<TimeSpan>("AvailableTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(13) CHARACTER SET utf8mb4")
                        .HasMaxLength(13);

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<TimeSpan>("End")
                        .HasColumnType("time(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Employee", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("BusinessUnitId")
                        .HasColumnType("int");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Direct")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DirectorNumber")
                        .HasColumnType("int");

                    b.Property<bool>("Hourly")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("ManagerNumber")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Number");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("ContractId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PositionId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Interno.Inventory.Models.Item", b =>
                {
                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Alias")
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<float>("Height")
                        .HasColumnType("float");

                    b.Property<float>("Length")
                        .HasColumnType("float");

                    b.Property<float>("MaxOrderQty")
                        .HasColumnType("float");

                    b.Property<float>("MinOrderQty")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<float>("OrderMultiple")
                        .HasColumnType("float");

                    b.Property<float>("ReorderPoint")
                        .HasColumnType("float");

                    b.Property<string>("Revision")
                        .HasColumnType("varchar(5) CHARACTER SET utf8mb4")
                        .HasMaxLength(5);

                    b.Property<float>("SafetyStock")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("float");

                    b.Property<float>("Width")
                        .HasColumnType("float");

                    b.HasKey("Guid", "Code");

                    b.HasIndex("CategoryId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Interno.Inventory.Models.Partnership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(15) CHARACTER SET utf8mb4")
                        .HasMaxLength(15);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Partnership");
                });

            modelBuilder.Entity("Interno.Inventory.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("Interno.Inventory.Models.Warehouse", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(13) CHARACTER SET utf8mb4")
                        .HasMaxLength(13);

                    b.Property<bool>("Active")
                        .HasColumnType("TINYINT(1)");

                    b.Property<float>("Capacity")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("UnitCode")
                        .HasColumnType("varchar(4) CHARACTER SET utf8mb4")
                        .HasMaxLength(4);

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Code");

                    b.HasIndex("FacilityId");

                    b.HasIndex("GroupId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UnitCode");

                    b.ToTable("Warehouse");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Warehouse");
                });

            modelBuilder.Entity("Interno.Inventory.Models.WarehouseGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("WarehouseGroup");
                });

            modelBuilder.Entity("Interno.Inventory.Models.WarehouseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Decription")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("WarehouseType");
                });

            modelBuilder.Entity("Interno.Production.Models.Downtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<int?>("AssignToNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ClosedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CommitDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<DateTime>("Escalation")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<int>("RequestNumber")
                        .HasColumnType("int");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AssignToNumber");

                    b.HasIndex("IssueId");

                    b.HasIndex("RequestNumber");

                    b.HasIndex("ResultId");

                    b.ToTable("Downtime");
                });

            modelBuilder.Entity("Interno.Production.Models.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Facility");
                });

            modelBuilder.Entity("Interno.Production.Models.HourByHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Hour")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<int>("Pieces")
                        .HasColumnType("int");

                    b.Property<string>("ResourceCode")
                        .IsRequired()
                        .HasColumnType("varchar(13) CHARACTER SET utf8mb4");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceCode");

                    b.HasIndex("ResultId");

                    b.ToTable("HourByHour");
                });

            modelBuilder.Entity("Interno.Production.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Issue");
                });

            modelBuilder.Entity("Interno.Production.Models.Labor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ResultId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber");

                    b.HasIndex("ResultId");

                    b.HasIndex("TypeId");

                    b.ToTable("Labor");
                });

            modelBuilder.Entity("Interno.Production.Models.LaborType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("LaborType");
                });

            modelBuilder.Entity("Interno.Production.Models.OperationTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<double>("Inprovement")
                        .HasColumnType("double");

                    b.Property<int>("Keying")
                        .HasColumnType("int");

                    b.Property<double>("LMPU")
                        .HasColumnType("double");

                    b.Property<decimal>("OffSet")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Operators")
                        .HasColumnType("int");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Repeat")
                        .HasColumnType("int");

                    b.Property<int?>("RoutId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("RunTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("SetTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("WarehouseCode")
                        .HasColumnType("varchar(13) CHARACTER SET utf8mb4");

                    b.Property<string>("WorkControl")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("RoutId");

                    b.HasIndex("WarehouseCode");

                    b.ToTable("OperationTime");
                });

            modelBuilder.Entity("Interno.Production.Models.Planning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Comments2")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Employee")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EmployeeReceived")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("KitDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("OperationTimeId")
                        .HasColumnType("int");

                    b.Property<string>("Order")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("OrderQty")
                        .HasColumnType("int");

                    b.Property<string>("PO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SO")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SOLine")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("WHSUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("altBOM")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("OperationTimeId");

                    b.ToTable("Plannings");
                });

            modelBuilder.Entity("Interno.Production.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Actual")
                        .HasColumnType("int");

                    b.Property<double>("Availability")
                        .HasColumnType("double");

                    b.Property<TimeSpan>("AvailableTime")
                        .HasColumnType("time(6)");

                    b.Property<int?>("BreaksId")
                        .HasColumnType("int");

                    b.Property<double>("Capacity")
                        .HasColumnType("double");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date1")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date2")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Eficiency")
                        .HasColumnType("double");

                    b.Property<double>("FirstPassYield")
                        .HasColumnType("double");

                    b.Property<DateTime>("InitialTime")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Inprovement")
                        .HasColumnType("double");

                    b.Property<string>("Item")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("LMPU")
                        .HasColumnType("double");

                    b.Property<TimeSpan>("LeadTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("LeaderNumber")
                        .HasColumnType("int");

                    b.Property<double>("OE")
                        .HasColumnType("double");

                    b.Property<double>("OEE")
                        .HasColumnType("double");

                    b.Property<double>("OEE1")
                        .HasColumnType("double");

                    b.Property<TimeSpan>("OperativeTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("Operators")
                        .HasColumnType("int");

                    b.Property<int>("OrderQty")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("OverTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("OverTimeEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlanQty")
                        .HasColumnType("int");

                    b.Property<string>("Planner")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("ProductiveTime")
                        .HasColumnType("time(6)");

                    b.Property<double>("Rate")
                        .HasColumnType("double");

                    b.Property<string>("ResourceCode")
                        .IsRequired()
                        .HasColumnType("varchar(13) CHARACTER SET utf8mb4");

                    b.Property<DateTime>("SMKTDate")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("ScheduledOperatingTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("ScheduledStops")
                        .HasColumnType("time(6)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SubResourceCode")
                        .HasColumnType("varchar(13) CHARACTER SET utf8mb4");

                    b.Property<int>("SupervisorNumber")
                        .HasColumnType("int");

                    b.Property<double>("TEP")
                        .HasColumnType("double");

                    b.Property<TimeSpan>("TakTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("WHSDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkOrder")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("WorkOrderId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("BreaksId");

                    b.HasIndex("ResourceCode");

                    b.HasIndex("ShiftId");

                    b.HasIndex("SubResourceCode");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Interno.Production.Models.ResultWorkOrder", b =>
                {
                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.Property<string>("WorkOrderId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("ResultId", "WorkOrderId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("ResultWorkOrder");
                });

            modelBuilder.Entity("Interno.Production.Models.Rout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(13) CHARACTER SET utf8mb4")
                        .HasMaxLength(13);

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasColumnType("varchar(5) CHARACTER SET utf8mb4")
                        .HasMaxLength(5);

                    b.Property<string>("Target")
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("Rout");
                });

            modelBuilder.Entity("Interno.Production.Models.Tracking", b =>
                {
                    b.Property<string>("Alias")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Close")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CloseEmployeeNumber")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("Item")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("OperationTimeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Reject")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RejectEmployeeNumber")
                        .HasColumnType("int");

                    b.Property<string>("ResourceCode")
                        .HasColumnType("varchar(13) CHARACTER SET utf8mb4");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<string>("Responsible")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Series")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sheet")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Start")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("StartEmployeeNumber")
                        .HasColumnType("int");

                    b.Property<string>("Target")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasIndex("CloseEmployeeNumber");

                    b.HasIndex("OperationTimeId");

                    b.HasIndex("RejectEmployeeNumber");

                    b.HasIndex("ResourceCode");

                    b.HasIndex("StartEmployeeNumber");

                    b.ToTable("Tracking");
                });

            modelBuilder.Entity("Interno.Production.Models.WorkOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Affected")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Alias")
                        .HasColumnType("varchar(45) CHARACTER SET utf8mb4")
                        .HasMaxLength(45);

                    b.Property<bool>("Approved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Cost")
                        .HasColumnType("double");

                    b.Property<TimeSpan>("Downtime")
                        .HasColumnType("time(6)");

                    b.Property<double>("EstimatedCost")
                        .HasColumnType("double");

                    b.Property<TimeSpan>("EstimatedTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("Finish")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FinishItemCode")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<long>("Lot")
                        .HasColumnType("bigint");

                    b.Property<int>("ManufQty")
                        .HasColumnType("int");

                    b.Property<int>("MaterialStatus")
                        .HasColumnType("int");

                    b.Property<int?>("OperationTimeId")
                        .HasColumnType("int");

                    b.Property<int>("OrderQty")
                        .HasColumnType("int");

                    b.Property<string>("Planner")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<DateTime>("Request")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Responsible")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Review")
                        .HasColumnType("varchar(5) CHARACTER SET utf8mb4")
                        .HasMaxLength(5);

                    b.Property<int?>("RoutId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Target")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<TimeSpan>("Trascurred")
                        .HasColumnType("time(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UMCode")
                        .HasColumnType("varchar(4) CHARACTER SET utf8mb4")
                        .HasMaxLength(4);

                    b.HasKey("Id");

                    b.HasIndex("OperationTimeId");

                    b.HasIndex("RoutId");

                    b.HasIndex("UMCode");

                    b.ToTable("WorkOrder");
                });

            modelBuilder.Entity("Interno.Users.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Interno.Production.Models.ProductionArea", b =>
                {
                    b.HasBaseType("Interno.HumanResource.Models.Catalog.Area");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.HasIndex("FacilityId");

                    b.HasDiscriminator().HasValue("ProductionArea");
                });

            modelBuilder.Entity("Interno.Production.Models.Resource", b =>
                {
                    b.HasBaseType("Interno.Inventory.Models.Warehouse");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("BreakGroupId")
                        .HasColumnType("int");

                    b.HasIndex("AreaId");

                    b.HasIndex("BreakGroupId");

                    b.HasDiscriminator().HasValue("Resource");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.Address", b =>
                {
                    b.HasOne("Interno.Domain.Catalog.Person", null)
                        .WithMany("Address")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.Company", b =>
                {
                    b.HasOne("Interno.Domain.Catalog.Phone", "BussinesPhone")
                        .WithMany()
                        .HasForeignKey("BussinesPhoneId");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.Contact", b =>
                {
                    b.HasOne("Interno.Domain.Catalog.Company", "Company")
                        .WithMany("Contacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.Domain.Catalog.Person", "Person")
                        .WithMany("Contact")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Interno.Domain.Catalog.License", b =>
                {
                    b.HasOne("Interno.Domain.Catalog.Person", null)
                        .WithMany("License")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.Location", b =>
                {
                    b.HasOne("Interno.Domain.Catalog.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.Mail", b =>
                {
                    b.HasOne("Interno.Domain.Catalog.Contact", null)
                        .WithMany("Mails")
                        .HasForeignKey("ContactId");

                    b.HasOne("Interno.Domain.Catalog.Person", null)
                        .WithMany("Mail")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.Person", b =>
                {
                    b.HasOne("Interno.Domain.Catalog.BloodType", "BloodType")
                        .WithMany()
                        .HasForeignKey("BloodTypeGroup");
                });

            modelBuilder.Entity("Interno.Domain.Catalog.Phone", b =>
                {
                    b.HasOne("Interno.Domain.Catalog.Contact", null)
                        .WithMany("Phones")
                        .HasForeignKey("ContactId");

                    b.HasOne("Interno.Domain.Catalog.Person", null)
                        .WithMany("Phone")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.Break", b =>
                {
                    b.HasOne("Interno.HumanResource.Models.Catalog.BreaksGroup", "BreakGroup")
                        .WithMany("Breaks")
                        .HasForeignKey("BreakGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.HumanResource.Models.Catalog.BreakType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.BreaksGroup", b =>
                {
                    b.HasOne("Interno.HumanResource.Models.Catalog.Shift", null)
                        .WithMany("BreaksGroups")
                        .HasForeignKey("ShiftId");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.JobPosition", b =>
                {
                    b.HasOne("Interno.HumanResource.Models.Catalog.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("Interno.HumanResource.Models.Catalog.Autority", "Autority")
                        .WithMany()
                        .HasForeignKey("AutorityId");

                    b.HasOne("Interno.HumanResource.Models.Catalog.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Employee", b =>
                {
                    b.HasOne("Interno.HumanResource.Models.Catalog.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId");

                    b.HasOne("Interno.HumanResource.Models.Catalog.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId");

                    b.HasOne("Interno.Domain.Catalog.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.HumanResource.Models.Catalog.JobPosition", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.HumanResource.Models.Catalog.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Interno.Inventory.Models.Item", b =>
                {
                    b.HasOne("Interno.Inventory.Models.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("Interno.Inventory.Models.Warehouse", b =>
                {
                    b.HasOne("Interno.Production.Models.Facility", null)
                        .WithMany("Warehouses")
                        .HasForeignKey("FacilityId");

                    b.HasOne("Interno.Inventory.Models.WarehouseGroup", "Group")
                        .WithMany("Warehouses")
                        .HasForeignKey("GroupId");

                    b.HasOne("Interno.Inventory.Models.WarehouseType", "Type")
                        .WithMany("Warehouses")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.Domain.Catalog.UM", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitCode");
                });

            modelBuilder.Entity("Interno.Production.Models.Downtime", b =>
                {
                    b.HasOne("Interno.HumanResource.Models.Employee", "AssignTo")
                        .WithMany()
                        .HasForeignKey("AssignToNumber");

                    b.HasOne("Interno.Production.Models.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.HumanResource.Models.Employee", "Request")
                        .WithMany()
                        .HasForeignKey("RequestNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.Production.Models.Result", "Result")
                        .WithMany("Downtime")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Interno.Production.Models.Facility", b =>
                {
                    b.HasOne("Interno.Domain.Catalog.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("Interno.Production.Models.HourByHour", b =>
                {
                    b.HasOne("Interno.Production.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.Production.Models.Result", "Result")
                        .WithMany("HourByHour")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Interno.Production.Models.Labor", b =>
                {
                    b.HasOne("Interno.HumanResource.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.Production.Models.Result", null)
                        .WithMany("Labor")
                        .HasForeignKey("ResultId");

                    b.HasOne("Interno.Production.Models.LaborType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");
                });

            modelBuilder.Entity("Interno.Production.Models.OperationTime", b =>
                {
                    b.HasOne("Interno.Production.Models.Rout", null)
                        .WithMany("Operations")
                        .HasForeignKey("RoutId");

                    b.HasOne("Interno.Inventory.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseCode");
                });

            modelBuilder.Entity("Interno.Production.Models.Planning", b =>
                {
                    b.HasOne("Interno.Production.Models.OperationTime", "OperationTime")
                        .WithMany()
                        .HasForeignKey("OperationTimeId");
                });

            modelBuilder.Entity("Interno.Production.Models.Result", b =>
                {
                    b.HasOne("Interno.HumanResource.Models.Catalog.BreaksGroup", "Breaks")
                        .WithMany()
                        .HasForeignKey("BreaksId");

                    b.HasOne("Interno.Production.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.HumanResource.Models.Catalog.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.Production.Models.Resource", "SubResource")
                        .WithMany()
                        .HasForeignKey("SubResourceCode");

                    b.HasOne("Interno.Production.Models.WorkOrder", null)
                        .WithMany("Results")
                        .HasForeignKey("WorkOrderId");
                });

            modelBuilder.Entity("Interno.Production.Models.ResultWorkOrder", b =>
                {
                    b.HasOne("Interno.Production.Models.Result", "Result")
                        .WithMany("Orders")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.Production.Models.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Interno.Production.Models.Tracking", b =>
                {
                    b.HasOne("Interno.HumanResource.Models.Employee", "CloseEmployee")
                        .WithMany()
                        .HasForeignKey("CloseEmployeeNumber");

                    b.HasOne("Interno.Production.Models.OperationTime", "OperationTime")
                        .WithMany()
                        .HasForeignKey("OperationTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.HumanResource.Models.Employee", "RejectEmployee")
                        .WithMany()
                        .HasForeignKey("RejectEmployeeNumber");

                    b.HasOne("Interno.Production.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceCode");

                    b.HasOne("Interno.HumanResource.Models.Employee", "StartEmployee")
                        .WithMany()
                        .HasForeignKey("StartEmployeeNumber");
                });

            modelBuilder.Entity("Interno.Production.Models.WorkOrder", b =>
                {
                    b.HasOne("Interno.Production.Models.OperationTime", "OperationTime")
                        .WithMany()
                        .HasForeignKey("OperationTimeId");

                    b.HasOne("Interno.Production.Models.Rout", "Rout")
                        .WithMany()
                        .HasForeignKey("RoutId");

                    b.HasOne("Interno.Domain.Catalog.UM", "UM")
                        .WithMany()
                        .HasForeignKey("UMCode");
                });

            modelBuilder.Entity("Interno.Users.Entities.User", b =>
                {
                    b.OwnsMany("Interno.Users.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("datetime(6)");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<string>("RevokedByToken")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<string>("Token")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });
                });

            modelBuilder.Entity("Interno.Production.Models.ProductionArea", b =>
                {
                    b.HasOne("Interno.Production.Models.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Interno.Production.Models.Resource", b =>
                {
                    b.HasOne("Interno.Production.Models.ProductionArea", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("Interno.HumanResource.Models.Catalog.BreaksGroup", "BreakGroup")
                        .WithMany()
                        .HasForeignKey("BreakGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
