# Generic single-database configuration.


"""restore_external_contacts

Revision ID: 73964464b417
Revises: a6054c79a22f
Create Date: 2026-05-21 16:56:44.611597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73964464b417'
down_revision: Union[str, None] = 'a6054c79a22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('collaborator_id', sa.UUID(), nullable=True),
    sa.Column('external_contact_id', sa.UUID(), nullable=True),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('record_id', sa.String(length=100), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_collaborator_id'), 'audit_logs', ['collaborator_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_external_contact_id'), 'audit_logs', ['external_contact_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_group_id'), 'audit_logs', ['group_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('business_groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_groups_name'), 'business_groups', ['name'], unique=False)
    op.create_table('enumerations',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('translation_key', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'key', 'company_id', name='uq_enum_type_key_company')
    )
    op.create_index(op.f('ix_enumerations_company_id'), 'enumerations', ['company_id'], unique=False)
    op.create_index(op.f('ix_enumerations_group_id'), 'enumerations', ['group_id'], unique=False)
    op.create_index(op.f('ix_enumerations_key'), 'enumerations', ['key'], unique=False)
    op.create_index(op.f('ix_enumerations_tenant_id'), 'enumerations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_enumerations_type'), 'enumerations', ['type'], unique=False)
    op.create_index('ix_enumerations_type_company_active', 'enumerations', ['type', 'company_id', 'is_active'], unique=False)
    op.create_table('external_contacts',
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_contacts_company_id'), 'external_contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_external_contacts_group_id'), 'external_contacts', ['group_id'], unique=False)
    op.create_index(op.f('ix_external_contacts_tenant_id'), 'external_contacts', ['tenant_id'], unique=False)
    op.create_table('file_metadata',
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('service_source', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_metadata_company_id'), 'file_metadata', ['company_id'], unique=False)
    op.create_index(op.f('ix_file_metadata_group_id'), 'file_metadata', ['group_id'], unique=False)
    op.create_index(op.f('ix_file_metadata_key'), 'file_metadata', ['key'], unique=False)
    op.create_index(op.f('ix_file_metadata_tenant_id'), 'file_metadata', ['tenant_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('inventory_locations',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Primary scan code. Format: PA-SEC-NV-POS (e.g. 01-05-02-A)'),
    sa.Column('aisle', sa.String(length=10), nullable=True, comment='Pasillo'),
    sa.Column('section', sa.String(length=10), nullable=True, comment='Columna/Bay'),
    sa.Column('level', sa.String(length=10), nullable=True, comment='Nivel/Shelf'),
    sa.Column('bin_slot', sa.String(length=10), nullable=True, comment='Gaveta/Bin'),
    sa.Column('zone_type', sa.String(length=20), nullable=False, comment='Functional zone: RECEIVING, STORAGE, PICKING, QUALITY, SHIPPING, TRANSIT'),
    sa.Column('storage_type', sa.String(length=20), nullable=False, comment='Environmental requirement: DRY, COLD, HAZMAT, LOCKED'),
    sa.Column('is_multisku', sa.Boolean(), nullable=False, comment='If False, only one SKU is allowed (e.g. medical/regulated items)'),
    sa.Column('velocity_code', sa.String(length=1), nullable=True, comment='A=High rotation (near shipping), B=Medium, C=Slow/Dead stock'),
    sa.Column('max_capacity_units', sa.Numeric(precision=15, scale=4), nullable=False, comment='Max units (pieces). 0 = unlimited.'),
    sa.Column('max_weight_kg', sa.Numeric(precision=15, scale=4), nullable=False, comment='Max weight in kg. 0 = unlimited. SAFETY-CRITICAL: no manager override.'),
    sa.Column('width_cm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('depth_cm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_units', sa.Numeric(precision=15, scale=4), nullable=False, comment='Current unit count. Denormalized cache — updated atomically.'),
    sa.Column('current_weight_kg', sa.Numeric(precision=15, scale=4), nullable=False, comment='Current weight in kg. Denormalized cache — updated atomically.'),
    sa.Column('is_virtual', sa.Boolean(), nullable=False, comment='True for system-managed zones: SYS_RECEIVING, SYS_TRANSIT, SYS_QUALITY'),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'warehouse_id', 'code', name='uq_location_per_warehouse')
    )
    op.create_index(op.f('ix_inventory_locations_code'), 'inventory_locations', ['code'], unique=False)
    op.create_index(op.f('ix_inventory_locations_company_id'), 'inventory_locations', ['company_id'], unique=False)
    op.create_index(op.f('ix_inventory_locations_group_id'), 'inventory_locations', ['group_id'], unique=False)
    op.create_index(op.f('ix_inventory_locations_tenant_id'), 'inventory_locations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_locations_warehouse_id'), 'inventory_locations', ['warehouse_id'], unique=False)
    op.create_table('security_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('collaborator_id', sa.UUID(), nullable=True),
    sa.Column('access_method', sa.String(length=50), nullable=False),
    sa.Column('identity_identifier', sa.String(length=255), nullable=False),
    sa.Column('roles_snapshot', sa.JSON(), nullable=True),
    sa.Column('scopes_snapshot', sa.JSON(), nullable=True),
    sa.Column('terminal_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_audit_logs_collaborator_id'), 'security_audit_logs', ['collaborator_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_company_id'), 'security_audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_user_id'), 'security_audit_logs', ['user_id'], unique=False)
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('parent_group_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('default_tax_rate', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['parent_group_id'], ['business_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_parent_group_id'), 'companies', ['parent_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_parent_group_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_security_audit_logs_user_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_company_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_collaborator_id'), table_name='security_audit_logs')
    op.drop_table('security_audit_logs')
    op.drop_index(op.f('ix_inventory_locations_warehouse_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_tenant_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_group_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_company_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_code'), table_name='inventory_locations')
    op.drop_table('inventory_locations')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_file_metadata_tenant_id'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_key'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_group_id'), table_name='file_metadata')
    op.drop_index(op.f('ix_file_metadata_company_id'), table_name='file_metadata')
    op.drop_table('file_metadata')
    op.drop_index(op.f('ix_external_contacts_tenant_id'), table_name='external_contacts')
    op.drop_index(op.f('ix_external_contacts_group_id'), table_name='external_contacts')
    op.drop_index(op.f('ix_external_contacts_company_id'), table_name='external_contacts')
    op.drop_table('external_contacts')
    op.drop_index('ix_enumerations_type_company_active', table_name='enumerations')
    op.drop_index(op.f('ix_enumerations_type'), table_name='enumerations')
    op.drop_index(op.f('ix_enumerations_tenant_id'), table_name='enumerations')
    op.drop_index(op.f('ix_enumerations_key'), table_name='enumerations')
    op.drop_index(op.f('ix_enumerations_group_id'), table_name='enumerations')
    op.drop_index(op.f('ix_enumerations_company_id'), table_name='enumerations')
    op.drop_table('enumerations')
    op.drop_index(op.f('ix_business_groups_name'), table_name='business_groups')
    op.drop_table('business_groups')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_group_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_external_contact_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_collaborator_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
