# Generic single-database configuration.


"""add_department_model

Revision ID: a6054c79a22f
Revises: 001_add_audit_logs_hcm
Create Date: 2026-05-20 19:11:45.314766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6054c79a22f'
down_revision: Union[str, None] = '001_add_audit_logs_hcm'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_department_code_company')
    )
    op.create_index(op.f('ix_departments_company_id'), 'departments', ['company_id'], unique=False)
    op.create_index(op.f('ix_departments_group_id'), 'departments', ['group_id'], unique=False)
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    op.drop_table('external_contacts')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_company_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_correlation_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_group_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_record_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_table_name', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.add_column('collaborators', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_collaborators_company_id'), 'collaborators', ['company_id'], unique=False)
    op.create_index(op.f('ix_collaborators_department_id'), 'collaborators', ['department_id'], unique=False)
    op.create_index(op.f('ix_collaborators_group_id'), 'collaborators', ['group_id'], unique=False)
    op.create_index(op.f('ix_collaborators_home_warehouse_id'), 'collaborators', ['home_warehouse_id'], unique=False)
    op.create_index(op.f('ix_collaborators_m3_operator_id'), 'collaborators', ['m3_operator_id'], unique=False)
    op.create_index(op.f('ix_collaborators_rfid_tag'), 'collaborators', ['rfid_tag'], unique=False)
    op.create_index(op.f('ix_collaborators_supervisor_id'), 'collaborators', ['supervisor_id'], unique=False)
    op.create_index(op.f('ix_collaborators_tenant_id'), 'collaborators', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_collaborators_translation_key'), 'collaborators', ['translation_key'], unique=False)
    op.create_index(op.f('ix_collaborators_user_id'), 'collaborators', ['user_id'], unique=False)
    op.create_foreign_key(None, 'collaborators', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_column('collaborators', 'department')
    op.create_index(op.f('ix_hr_tenant_configs_company_id'), 'hr_tenant_configs', ['company_id'], unique=False)
    op.create_index(op.f('ix_hr_tenant_configs_group_id'), 'hr_tenant_configs', ['group_id'], unique=False)
    op.create_index(op.f('ix_hr_tenant_configs_tenant_id'), 'hr_tenant_configs', ['tenant_id'], unique=False)
    op.drop_column('hr_tenant_configs', 'shift_schedules')
    op.drop_column('hr_tenant_configs', 'payroll_frequency')
    op.drop_column('hr_tenant_configs', 'overtime_policy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_tenant_configs', sa.Column('overtime_policy', sa.VARCHAR(length=50), server_default=sa.text("'STANDARD'::character varying"), autoincrement=False, nullable=False))
    op.add_column('hr_tenant_configs', sa.Column('payroll_frequency', sa.VARCHAR(length=20), server_default=sa.text("'WEEKLY'::character varying"), autoincrement=False, nullable=False))
    op.add_column('hr_tenant_configs', sa.Column('shift_schedules', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_hr_tenant_configs_tenant_id'), table_name='hr_tenant_configs')
    op.drop_index(op.f('ix_hr_tenant_configs_group_id'), table_name='hr_tenant_configs')
    op.drop_index(op.f('ix_hr_tenant_configs_company_id'), table_name='hr_tenant_configs')
    op.add_column('collaborators', sa.Column('department', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'collaborators', type_='foreignkey')
    op.drop_index(op.f('ix_collaborators_user_id'), table_name='collaborators')
    op.drop_index(op.f('ix_collaborators_translation_key'), table_name='collaborators')
    op.drop_index(op.f('ix_collaborators_tenant_id'), table_name='collaborators')
    op.drop_index(op.f('ix_collaborators_supervisor_id'), table_name='collaborators')
    op.drop_index(op.f('ix_collaborators_rfid_tag'), table_name='collaborators')
    op.drop_index(op.f('ix_collaborators_m3_operator_id'), table_name='collaborators')
    op.drop_index(op.f('ix_collaborators_home_warehouse_id'), table_name='collaborators')
    op.drop_index(op.f('ix_collaborators_group_id'), table_name='collaborators')
    op.drop_index(op.f('ix_collaborators_department_id'), table_name='collaborators')
    op.drop_index(op.f('ix_collaborators_company_id'), table_name='collaborators')
    op.drop_column('collaborators', 'department_id')
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('collaborator_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('external_contact_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('client_ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_tenant_id', 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_logs_table_name', 'audit_logs', ['table_name'], unique=False)
    op.create_index('ix_audit_logs_record_id', 'audit_logs', ['record_id'], unique=False)
    op.create_index('ix_audit_logs_group_id', 'audit_logs', ['group_id'], unique=False)
    op.create_index('ix_audit_logs_correlation_id', 'audit_logs', ['correlation_id'], unique=False)
    op.create_index('ix_audit_logs_company_id', 'audit_logs', ['company_id'], unique=False)
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_table('external_contacts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='external_contacts_pkey')
    )
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_group_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_company_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
