"""Genera la primera migración base con los modelos de Opportunity, ZoneConfig y AuditLog."""
# Revision generated by Alembic — ejecutar: alembic revision --autogenerate -m "initial_schema"
# Para aplicar: alembic upgrade head

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ── zone_configs ──────────────────────────────────────────────────────
    op.create_table(
        "zone_configs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("colonia", sa.String(200), nullable=False, unique=True),
        sa.Column("municipio", sa.Integer, nullable=False, server_default="2"),
        sa.Column("valor_m2", sa.Numeric(12, 2), nullable=False),
        sa.Column("source", sa.String(50), server_default="manual"),
        sa.Column("updated_at", sa.DateTime(timezone=True)),
        sa.Column("updated_by", sa.String(36), nullable=True),
    )
    op.create_index("ix_zone_configs_colonia", "zone_configs", ["colonia"])

    # ── opportunities ─────────────────────────────────────────────────────
    opportunity_status = sa.Enum(
        "Scouting", "Due Diligence", "Negociación",
        "Adjudicación/Cierre", "Venta", "Descartado",
        name="opportunity_status"
    )
    legal_status = sa.Enum(
        "Libre", "Intestado", "Litigio", "Embargado", "Desconocido",
        name="legal_status"
    )
    op.create_table(
        "opportunities",
        sa.Column("cve_cat", sa.String(50), primary_key=True),
        sa.Column("lat", sa.Numeric(11, 7), nullable=True),
        sa.Column("lng", sa.Numeric(11, 7), nullable=True),
        sa.Column("direccion_catastral", sa.String(300), nullable=True),
        sa.Column("colonia", sa.String(200), nullable=True),
        sa.Column("superficie", sa.Numeric(10, 2), nullable=True),
        sa.Column("propietario_rppc", sa.String(300), nullable=True),
        sa.Column("folio_real", sa.String(100), nullable=True),
        sa.Column("propietario_contacto", sa.JSON, nullable=True),
        sa.Column("adeudo_total", sa.Numeric(14, 2), nullable=True),
        sa.Column("ultimo_pago", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valor_m2_zona", sa.Numeric(12, 2), nullable=True),
        sa.Column("estimated_market_value", sa.Numeric(14, 2), nullable=True),
        sa.Column("precio_adquisicion", sa.Numeric(14, 2), nullable=True),
        sa.Column("gastos_legales", sa.Numeric(12, 2), server_default="50000"),
        sa.Column("risk_buffer_percentage", sa.Numeric(5, 4), nullable=False, server_default="0.10"),
        sa.Column("projected_roi", sa.Numeric(14, 2), nullable=True),
        sa.Column("is_investment_opportunity", sa.Boolean, server_default="false"),
        sa.Column("status", opportunity_status, nullable=False, server_default="Scouting"),
        sa.Column("legal_status", legal_status, nullable=False, server_default="Desconocido"),
        sa.Column("needs_manual_data", sa.Boolean, server_default="false"),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(36), nullable=True),
    )
    op.create_index("ix_opportunities_status", "opportunities", ["status"])
    op.create_index("ix_opportunities_is_investment", "opportunities", ["is_investment_opportunity"])
    op.create_index("ix_opportunities_needs_manual", "opportunities", ["needs_manual_data"])

    # ── opportunity_audit_logs ────────────────────────────────────────────
    op.create_table(
        "opportunity_audit_logs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("opportunity_cve_cat", sa.String(50), sa.ForeignKey("opportunities.cve_cat", ondelete="CASCADE"), nullable=False),
        sa.Column("action", sa.String(100), nullable=False),
        sa.Column("previous_value", sa.String(200), nullable=True),
        sa.Column("new_value", sa.String(200), nullable=True),
        sa.Column("performed_by", sa.String(36), nullable=True),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("opportunity_audit_logs")
    op.drop_index("ix_opportunities_needs_manual", "opportunities")
    op.drop_index("ix_opportunities_is_investment", "opportunities")
    op.drop_index("ix_opportunities_status", "opportunities")
    op.drop_table("opportunities")
    op.drop_index("ix_zone_configs_colonia", "zone_configs")
    op.drop_table("zone_configs")
    sa.Enum(name="opportunity_status").drop(op.get_bind())
    sa.Enum(name="legal_status").drop(op.get_bind())
