"""fe63_inventory_locations_ssot

Revision ID: 5d92f2693957
Revises: 1e8e0d6b4a26
Create Date: 2026-04-20 18:36:53.957855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d92f2693957'
down_revision: Union[str, None] = '1e8e0d6b4a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_locations',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('max_capacity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'warehouse_id', 'code', name='uq_location_per_warehouse')
    )
    op.create_index(op.f('ix_inventory_locations_code'), 'inventory_locations', ['code'], unique=False)
    op.create_index(op.f('ix_inventory_locations_company_id'), 'inventory_locations', ['company_id'], unique=False)
    op.create_index(op.f('ix_inventory_locations_group_id'), 'inventory_locations', ['group_id'], unique=False)
    op.create_index(op.f('ix_inventory_locations_tenant_id'), 'inventory_locations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_locations_warehouse_id'), 'inventory_locations', ['warehouse_id'], unique=False)
    op.add_column('audit_logs', sa.Column('correlation_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('client_ip', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('audit_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audit_logs', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audit_logs', sa.Column('transaction_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('audit_logs', sa.Column('version_id', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('audit_logs', 'company_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='company_id::uuid')
    op.alter_column('audit_logs', 'group_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='group_id::uuid')
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('audit_logs', 'old_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_group_id'), 'audit_logs', ['group_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'trace_id')
    op.alter_column('partners', 'code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('partners', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=False)
    op.alter_column('price_agreements', 'document_reference',
               existing_type=sa.VARCHAR(length=250),
               comment='Folio o UUID S3 del contrato fisico escaneado',
               existing_nullable=True)
    op.alter_column('price_agreements', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('price_agreements', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('price_agreements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('price_agreements', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_price_agreements_active', table_name='price_agreements', postgresql_where='(valid_until IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_price_agreements_active', 'price_agreements', ['product_id', 'partner_id', 'currency'], unique=False, postgresql_where='(valid_until IS NULL)')
    op.alter_column('price_agreements', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('price_agreements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('price_agreements', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('price_agreements', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('price_agreements', 'document_reference',
               existing_type=sa.VARCHAR(length=250),
               comment=None,
               existing_comment='Folio o UUID S3 del contrato fisico escaneado',
               existing_nullable=True)
    op.alter_column('partners', 'name',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('partners', 'code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.add_column('audit_logs', sa.Column('trace_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_group_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('audit_logs', 'new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('audit_logs', 'group_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('audit_logs', 'version_id')
    op.drop_column('audit_logs', 'is_active')
    op.drop_column('audit_logs', 'transaction_id')
    op.drop_column('audit_logs', 'deleted_at')
    op.drop_column('audit_logs', 'updated_by')
    op.drop_column('audit_logs', 'created_by')
    op.drop_column('audit_logs', 'updated_at')
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('audit_logs', 'client_ip')
    op.drop_column('audit_logs', 'tenant_id')
    op.drop_column('audit_logs', 'correlation_id')
    op.drop_index(op.f('ix_inventory_locations_warehouse_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_tenant_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_group_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_company_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_locations_code'), table_name='inventory_locations')
    op.drop_table('inventory_locations')
    # ### end Alembic commands ###
