"""init_baseline

Revision ID: 7a41eb887dd9
Revises: 
Create Date: 2026-02-28 18:46:36.988168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a41eb887dd9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Obtener el inspector para verificar tablas existentes
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'product_brands' not in existing_tables:
        op.create_table('product_brands',
        sa.Column('company_id', sa.UUID(), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('translation_key', sa.String(length=100), nullable=True),
        sa.Column('group_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('transaction_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('version_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code', 'company_id', name='uq_brand_code_company')
        )
        op.create_index(op.f('ix_product_brands_code'), 'product_brands', ['code'], unique=False)
        op.create_index(op.f('ix_product_brands_company_id'), 'product_brands', ['company_id'], unique=False)
        op.create_index(op.f('ix_product_brands_group_id'), 'product_brands', ['group_id'], unique=False)
        op.create_index(op.f('ix_product_brands_translation_key'), 'product_brands', ['translation_key'], unique=False)
    
    if 'product_categories' not in existing_tables:
        op.create_table('product_categories',
        sa.Column('company_id', sa.UUID(), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('translation_key', sa.String(length=100), nullable=True),
        sa.Column('group_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('transaction_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('version_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code', 'company_id', name='uq_category_code_company')
        )
        op.create_index(op.f('ix_product_categories_code'), 'product_categories', ['code'], unique=False)
        op.create_index(op.f('ix_product_categories_company_id'), 'product_categories', ['company_id'], unique=False)
        op.create_index(op.f('ix_product_categories_group_id'), 'product_categories', ['group_id'], unique=False)
        op.create_index(op.f('ix_product_categories_translation_key'), 'product_categories', ['translation_key'], unique=False)
    
    if 'uoms' not in existing_tables:
        op.create_table('uoms',
        sa.Column('company_id', sa.UUID(), nullable=True),
        sa.Column('code', sa.String(length=10), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('plural', sa.String(length=50), nullable=True),
        sa.Column('conversion_factor', sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column('translation_key', sa.String(length=100), nullable=True),
        sa.Column('group_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('transaction_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('version_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code', 'company_id', name='uq_uom_code_company')
        )
        op.create_index(op.f('ix_uoms_code'), 'uoms', ['code'], unique=False)
        op.create_index(op.f('ix_uoms_company_id'), 'uoms', ['company_id'], unique=False)
        op.create_index(op.f('ix_uoms_group_id'), 'uoms', ['group_id'], unique=False)
        op.create_index(op.f('ix_uoms_translation_key'), 'uoms', ['translation_key'], unique=False)
    
    if 'products' not in existing_tables:
        op.create_table('products',
        sa.Column('sku', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('product_type', sa.Enum('GOODS', 'SERVICE', name='producttype'), nullable=False),
        sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'DISCONTINUED', name='productstatus'), nullable=False),
        sa.Column('category_id', sa.UUID(), nullable=True),
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column('group_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('transaction_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('version_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sku', 'company_id', name='_company_sku_uc')
        )
        op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
        op.create_index(op.f('ix_products_group_id'), 'products', ['group_id'], unique=False)
        op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    
    if 'product_versions' not in existing_tables:
        op.create_table('product_versions',
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('version_status', sa.Enum('DESIGN', 'EXPERIMENTAL', 'UNDER_REVIEW', 'PUBLISHED', 'DEPRECATED', 'ARCHIVED', 'DRAFT', name='versionstatus'), nullable=False),
        sa.Column('weight', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('dimensions', sa.JSON(), nullable=True),
        sa.Column('um_id', sa.UUID(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_validated', sa.Boolean(), nullable=False),
        sa.Column('change_reason', sa.Text(), nullable=True),
        sa.Column('technical_specs', sa.JSON(), nullable=True),
        sa.Column('approved_by', sa.UUID(), nullable=True),
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column('group_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('transaction_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('version_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.ForeignKeyConstraint(['um_id'], ['uoms.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('product_id', 'version_number', name='_product_version_uc')
        )
        op.create_index(op.f('ix_product_versions_company_id'), 'product_versions', ['company_id'], unique=False)
        op.create_index(op.f('ix_product_versions_group_id'), 'product_versions', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_versions_group_id'), table_name='product_versions')
    op.drop_index(op.f('ix_product_versions_company_id'), table_name='product_versions')
    op.drop_table('product_versions')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_group_id'), table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_uoms_translation_key'), table_name='uoms')
    op.drop_index(op.f('ix_uoms_group_id'), table_name='uoms')
    op.drop_index(op.f('ix_uoms_company_id'), table_name='uoms')
    op.drop_index(op.f('ix_uoms_code'), table_name='uoms')
    op.drop_table('uoms')
    op.drop_index(op.f('ix_product_categories_translation_key'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_group_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_company_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_code'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_product_brands_translation_key'), table_name='product_brands')
    op.drop_index(op.f('ix_product_brands_group_id'), table_name='product_brands')
    op.drop_index(op.f('ix_product_brands_company_id'), table_name='product_brands')
    op.drop_index(op.f('ix_product_brands_code'), table_name='product_brands')
    op.drop_table('product_brands')
    # ### end Alembic commands ###
