"""architecture_cleanup

Revision ID: 87e06c6c460a
Revises: 58e0de261a29
Create Date: 2026-04-05 16:45:47.261706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e06c6c460a'
down_revision: Union[str, None] = '58e0de261a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('warehouses',
    sa.Column('is_production_resource', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('PHYSICAL', 'VIRTUAL', 'TRANSIT', 'RESOURCE', 'EXT_PARTNER', name='warehousetype'), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=False)
    op.create_index(op.f('ix_warehouses_company_id'), 'warehouses', ['company_id'], unique=False)
    op.create_index(op.f('ix_warehouses_group_id'), 'warehouses', ['group_id'], unique=False)
    op.create_index(op.f('ix_warehouses_tenant_id'), 'warehouses', ['tenant_id'], unique=False)
    op.add_column('movement_concepts', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('movement_concepts', 'code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('movement_concepts', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_movement_concepts_group_id'), 'movement_concepts', ['group_id'], unique=False)
    op.drop_index('ix_product_prices_valid_until', table_name='product_prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_product_prices_valid_until', 'product_prices', ['valid_until'], unique=False)
    op.drop_index(op.f('ix_movement_concepts_group_id'), table_name='movement_concepts')
    op.alter_column('movement_concepts', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('movement_concepts', 'code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('movement_concepts', 'description')
    op.drop_index(op.f('ix_warehouses_tenant_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_group_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_company_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
