"""phase_33_5_product_prices_and_fiscal_codes

Revision ID: bb3da9fcddfd
Revises: 2e91b58d7eac
Create Date: 2026-03-16 20:29:57.462977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3da9fcddfd'
down_revision: Union[str, None] = '2e91b58d7eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uom_conversions',
    sa.Column('from_uom_id', sa.UUID(), nullable=False),
    sa.Column('to_uom_id', sa.UUID(), nullable=False),
    sa.Column('factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_uom_id'], ['uoms.id'], ),
    sa.ForeignKeyConstraint(['to_uom_id'], ['uoms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_uom_id', 'to_uom_id', 'company_id', name='uq_uom_conversion_src_dest_company')
    )
    op.create_index(op.f('ix_uom_conversions_company_id'), 'uom_conversions', ['company_id'], unique=False)
    op.create_index(op.f('ix_uom_conversions_group_id'), 'uom_conversions', ['group_id'], unique=False)
    op.create_table('product_prices',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('price_list_index', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit_type', sa.Enum('BASE', 'SALE', name='product_price_unit_type'), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'product_id', 'price_list_index', 'unit_type', 'warehouse_id', 'currency', name='_product_price_unique_uc')
    )
    op.create_index(op.f('ix_product_prices_company_id'), 'product_prices', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_prices_group_id'), 'product_prices', ['group_id'], unique=False)
    op.create_index(op.f('ix_product_prices_product_id'), 'product_prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_prices_warehouse_id'), 'product_prices', ['warehouse_id'], unique=False)
    op.add_column('products', sa.Column('sat_product_code', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('hts_code', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('is_taxable', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('products', sa.Column('allow_price_override', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('products', sa.Column('min_order_qty', sa.Numeric(precision=12, scale=4), nullable=False, server_default=sa.text('0')))
    op.add_column('products', sa.Column('max_order_qty', sa.Numeric(precision=12, scale=4), nullable=False, server_default=sa.text('0')))
    op.add_column('products', sa.Column('safety_stock', sa.Numeric(precision=12, scale=4), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'safety_stock')
    op.drop_column('products', 'max_order_qty')
    op.drop_column('products', 'min_order_qty')
    op.drop_column('products', 'allow_price_override')
    op.drop_column('products', 'is_taxable')
    op.drop_column('products', 'hts_code')
    op.drop_column('products', 'sat_product_code')
    op.drop_index(op.f('ix_product_prices_warehouse_id'), table_name='product_prices')
    op.drop_index(op.f('ix_product_prices_product_id'), table_name='product_prices')
    op.drop_index(op.f('ix_product_prices_group_id'), table_name='product_prices')
    op.drop_index(op.f('ix_product_prices_company_id'), table_name='product_prices')
    op.drop_table('product_prices')
    op.drop_index(op.f('ix_uom_conversions_group_id'), table_name='uom_conversions')
    op.drop_index(op.f('ix_uom_conversions_company_id'), table_name='uom_conversions')
    op.drop_table('uom_conversions')
    # ### end Alembic commands ###
