"""add_partners_table

Revision ID: be0c6aad1657
Revises: b3c4d5e6f7a8
Create Date: 2026-04-03 20:24:12.837848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0c6aad1657'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create partners table (non-existing yet, so we can define it correctly)
    op.create_table('partners',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('type', sa.Enum('CUSTOMER', 'SUPPLIER', 'BOTH', name='partnertype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_code'), 'partners', ['code'], unique=False)
    op.create_index(op.f('ix_partners_company_id'), 'partners', ['company_id'], unique=False)
    op.create_index(op.f('ix_partners_group_id'), 'partners', ['group_id'], unique=False)
    op.create_index(op.f('ix_partners_tenant_id'), 'partners', ['tenant_id'], unique=False)

    # 2. Add companies columns with defaults
    op.add_column('companies', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.execute("UPDATE companies SET country_code = 'MX' WHERE country_code IS NULL")
    op.alter_column('companies', 'country_code', nullable=False)

    op.add_column('companies', sa.Column('base_currency', sa.String(length=3), nullable=True))
    op.execute("UPDATE companies SET base_currency = 'MXN' WHERE base_currency IS NULL")
    op.alter_column('companies', 'base_currency', nullable=False)

    # 3. Handle file_metadata tenant_id
    op.add_column('file_metadata', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.execute("UPDATE file_metadata SET tenant_id = '00000000-0000-0000-0000-000000000000' WHERE tenant_id IS NULL")
    # Note: Using a null-uuid since file_metadata might not have company_id directly to copy from
    op.create_index(op.f('ix_file_metadata_tenant_id'), 'file_metadata', ['tenant_id'], unique=False)
    op.alter_column('file_metadata', 'tenant_id', nullable=False)

    # 4. Fill existing null tenant_id from company_id
    TABLES_WITH_TENANT = [
        'product_brands', 'product_categories', 'product_prices', 
        'product_versions', 'products', 'uom_conversions', 'uoms'
    ]
    for table in TABLES_WITH_TENANT:
        op.execute(f"UPDATE {table} SET tenant_id = company_id WHERE tenant_id IS NULL AND company_id IS NOT NULL")
        # For those that might have both NULL (unlikely in this system), use a default
        op.execute(f"UPDATE {table} SET tenant_id = '00000000-0000-0000-0000-000000000000' WHERE tenant_id IS NULL")

    # 5. Now set nullable=False
    for table in TABLES_WITH_TENANT:
        op.alter_column(table, 'tenant_id', existing_type=sa.UUID(), nullable=False)

    # 6. Cleanup indexes (optional but based on autogen)
    # op.drop_index('ix_product_prices_valid_until', table_name='product_prices') # Avoid if already dropped or if needed
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uoms', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('uom_conversions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('products', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('product_versions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_product_prices_valid_until', 'product_prices', ['valid_until'], unique=False)
    op.alter_column('product_prices', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('product_categories', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('product_brands', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_file_metadata_tenant_id'), table_name='file_metadata')
    op.drop_column('file_metadata', 'tenant_id')
    op.drop_column('companies', 'base_currency')
    op.drop_column('companies', 'country_code')
    op.drop_index(op.f('ix_partners_tenant_id'), table_name='partners')
    op.drop_index(op.f('ix_partners_group_id'), table_name='partners')
    op.drop_index(op.f('ix_partners_company_id'), table_name='partners')
    op.drop_index(op.f('ix_partners_code'), table_name='partners')
    op.drop_table('partners')
    # ### end Alembic commands ###
