"""add translation_key to movement_concepts

Revision ID: f21020a05ace
Revises: 51c0b1772a4c
Create Date: 2026-05-16 04:55:59.593841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f21020a05ace'
down_revision: Union[str, None] = '51c0b1772a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_contacts',
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_contacts_company_id'), 'external_contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_external_contacts_group_id'), 'external_contacts', ['group_id'], unique=False)
    op.create_index(op.f('ix_external_contacts_tenant_id'), 'external_contacts', ['tenant_id'], unique=False)
    op.create_table('security_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('collaborator_id', sa.UUID(), nullable=True),
    sa.Column('access_method', sa.String(length=50), nullable=False),
    sa.Column('identity_identifier', sa.String(length=255), nullable=False),
    sa.Column('roles_snapshot', sa.JSON(), nullable=True),
    sa.Column('scopes_snapshot', sa.JSON(), nullable=True),
    sa.Column('terminal_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_audit_logs_collaborator_id'), 'security_audit_logs', ['collaborator_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_company_id'), 'security_audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_user_id'), 'security_audit_logs', ['user_id'], unique=False)
    op.create_table('partner_contacts',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('external_contact_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['external_contact_id'], ['external_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner_id', 'external_contact_id')
    )
    op.add_column('audit_logs', sa.Column('collaborator_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('external_contact_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_audit_logs_collaborator_id'), 'audit_logs', ['collaborator_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_external_contact_id'), 'audit_logs', ['external_contact_id'], unique=False)
    op.add_column('companies', sa.Column('default_tax_rate', sa.Numeric(), nullable=False))
    op.add_column('enumerations', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('enumerations', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('enumerations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('enumerations', sa.Column('transaction_id', sa.UUID(), nullable=True))
    op.add_column('enumerations', sa.Column('version_id', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('enumerations', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_enumerations_group_id'), 'enumerations', ['group_id'], unique=False)
    op.create_index(op.f('ix_enumerations_tenant_id'), 'enumerations', ['tenant_id'], unique=False)
    op.drop_column('enumerations', 'is_deleted')
    op.add_column('inventory_locations', sa.Column('aisle', sa.String(length=10), nullable=True, comment='Pasillo'))
    op.add_column('inventory_locations', sa.Column('section', sa.String(length=10), nullable=True, comment='Columna/Bay'))
    op.add_column('inventory_locations', sa.Column('level', sa.String(length=10), nullable=True, comment='Nivel/Shelf'))
    op.add_column('inventory_locations', sa.Column('bin_slot', sa.String(length=10), nullable=True, comment='Gaveta/Bin'))
    op.add_column('inventory_locations', sa.Column('zone_type', sa.String(length=20), nullable=False, comment='Functional zone: RECEIVING, STORAGE, PICKING, QUALITY, SHIPPING, TRANSIT'))
    op.add_column('inventory_locations', sa.Column('storage_type', sa.String(length=20), nullable=False, comment='Environmental requirement: DRY, COLD, HAZMAT, LOCKED'))
    op.add_column('inventory_locations', sa.Column('is_multisku', sa.Boolean(), nullable=False, comment='If False, only one SKU is allowed (e.g. medical/regulated items)'))
    op.add_column('inventory_locations', sa.Column('velocity_code', sa.String(length=1), nullable=True, comment='A=High rotation (near shipping), B=Medium, C=Slow/Dead stock'))
    op.add_column('inventory_locations', sa.Column('max_capacity_units', sa.Numeric(precision=15, scale=4), nullable=False, comment='Max units (pieces). 0 = unlimited.'))
    op.add_column('inventory_locations', sa.Column('max_weight_kg', sa.Numeric(precision=15, scale=4), nullable=False, comment='Max weight in kg. 0 = unlimited. SAFETY-CRITICAL: no manager override.'))
    op.add_column('inventory_locations', sa.Column('width_cm', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('inventory_locations', sa.Column('height_cm', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('inventory_locations', sa.Column('depth_cm', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('inventory_locations', sa.Column('current_units', sa.Numeric(precision=15, scale=4), nullable=False, comment='Current unit count. Denormalized cache — updated atomically.'))
    op.add_column('inventory_locations', sa.Column('current_weight_kg', sa.Numeric(precision=15, scale=4), nullable=False, comment='Current weight in kg. Denormalized cache — updated atomically.'))
    op.add_column('inventory_locations', sa.Column('is_virtual', sa.Boolean(), nullable=False, comment='True for system-managed zones: SYS_RECEIVING, SYS_TRANSIT, SYS_QUALITY'))
    op.alter_column('inventory_locations', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Primary scan code. Format: PA-SEC-NV-POS (e.g. 01-05-02-A)',
               existing_nullable=False)
    op.drop_constraint('inventory_locations_warehouse_id_fkey', 'inventory_locations', type_='foreignkey')
    op.drop_column('inventory_locations', 'max_capacity')
    op.drop_column('inventory_locations', 'zone')
    op.add_column('movement_concepts', sa.Column('translation_key', sa.String(length=100), nullable=True))
    op.alter_column('movement_concepts', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('movement_concepts', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_movement_concepts_translation_key'), 'movement_concepts', ['translation_key'], unique=False)
    op.add_column('partners', sa.Column('price_list_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'price_list_index')
    op.drop_index(op.f('ix_movement_concepts_translation_key'), table_name='movement_concepts')
    op.alter_column('movement_concepts', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('movement_concepts', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('movement_concepts', 'translation_key')
    op.add_column('inventory_locations', sa.Column('zone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('inventory_locations', sa.Column('max_capacity', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=False))
    op.create_foreign_key('inventory_locations_warehouse_id_fkey', 'inventory_locations', 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')
    op.alter_column('inventory_locations', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Primary scan code. Format: PA-SEC-NV-POS (e.g. 01-05-02-A)',
               existing_nullable=False)
    op.drop_column('inventory_locations', 'is_virtual')
    op.drop_column('inventory_locations', 'current_weight_kg')
    op.drop_column('inventory_locations', 'current_units')
    op.drop_column('inventory_locations', 'depth_cm')
    op.drop_column('inventory_locations', 'height_cm')
    op.drop_column('inventory_locations', 'width_cm')
    op.drop_column('inventory_locations', 'max_weight_kg')
    op.drop_column('inventory_locations', 'max_capacity_units')
    op.drop_column('inventory_locations', 'velocity_code')
    op.drop_column('inventory_locations', 'is_multisku')
    op.drop_column('inventory_locations', 'storage_type')
    op.drop_column('inventory_locations', 'zone_type')
    op.drop_column('inventory_locations', 'bin_slot')
    op.drop_column('inventory_locations', 'level')
    op.drop_column('inventory_locations', 'section')
    op.drop_column('inventory_locations', 'aisle')
    op.add_column('enumerations', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_enumerations_tenant_id'), table_name='enumerations')
    op.drop_index(op.f('ix_enumerations_group_id'), table_name='enumerations')
    op.alter_column('enumerations', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('enumerations', 'version_id')
    op.drop_column('enumerations', 'transaction_id')
    op.drop_column('enumerations', 'deleted_at')
    op.drop_column('enumerations', 'updated_by')
    op.drop_column('enumerations', 'created_by')
    op.drop_column('companies', 'default_tax_rate')
    op.drop_index(op.f('ix_audit_logs_external_contact_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_collaborator_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'external_contact_id')
    op.drop_column('audit_logs', 'collaborator_id')
    op.drop_table('partner_contacts')
    op.drop_index(op.f('ix_security_audit_logs_user_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_company_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_collaborator_id'), table_name='security_audit_logs')
    op.drop_table('security_audit_logs')
    op.drop_index(op.f('ix_external_contacts_tenant_id'), table_name='external_contacts')
    op.drop_index(op.f('ix_external_contacts_group_id'), table_name='external_contacts')
    op.drop_index(op.f('ix_external_contacts_company_id'), table_name='external_contacts')
    op.drop_table('external_contacts')
    # ### end Alembic commands ###
