// <auto-generated />
using System;
using Interno.Outset.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Interno.Outset.Migrations
{
    [DbContext(typeof(OutsetContext))]
    partial class OutsetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Interno.Domain.Catalog.UM", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Plural")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Code");

                    b.ToTable("UM");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.Break", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BreaksGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time(6)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreaksGroupId");

                    b.HasIndex("TypeId");

                    b.ToTable("Break");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.BreakType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.ToTable("BreakType");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.BreaksGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("BreaksGroup");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<TimeSpan>("AvailableTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("time(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("Interno.Inventory.Models.Partnership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Partnership");
                });

            modelBuilder.Entity("Interno.Inventory.Models.Warehouse", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("Capacity")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("UnitCode")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Code");

                    b.HasIndex("GroupId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UnitCode");

                    b.ToTable("Warehouse");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Warehouse");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Interno.Inventory.Models.WarehouseGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("WarehouseGroup");
                });

            modelBuilder.Entity("Interno.Inventory.Models.WarehouseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Decription")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("WarehouseType");
                });

            modelBuilder.Entity("Interno.Production.Models.Downtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("AssignToNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ClosedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CommitDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("Escalation")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<int?>("HourByHourId")
                        .HasColumnType("int");

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<int>("RequestNumber")
                        .HasColumnType("int");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("HourByHourId");

                    b.HasIndex("IssueId");

                    b.HasIndex("ResultId");

                    b.ToTable("Downtime");
                });

            modelBuilder.Entity("Interno.Production.Models.HourByHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmployeesQty")
                        .HasColumnType("int");

                    b.Property<DateTime>("Hour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Issues")
                        .HasColumnType("int");

                    b.Property<string>("Item")
                        .HasColumnType("longtext");

                    b.Property<int>("Meta")
                        .HasColumnType("int");

                    b.Property<double>("PaidHrs")
                        .HasColumnType("double");

                    b.Property<int>("Pieces")
                        .HasColumnType("int");

                    b.Property<string>("ResourceCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.Property<double>("StdTime")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("HourByHour");

                    b.HasDiscriminator<string>("Discriminator").HasValue("HourByHour");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Interno.Production.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Issue");
                });

            modelBuilder.Entity("Interno.Production.Models.Labor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResourceCode")
                        .HasColumnType("longtext");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("Labor");
                });

            modelBuilder.Entity("Interno.Production.Models.OperationTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<double>("Hours")
                        .HasColumnType("double");

                    b.Property<double>("Inprovement")
                        .HasColumnType("double");

                    b.Property<int>("Keying")
                        .HasColumnType("int");

                    b.Property<double>("LMPU")
                        .HasColumnType("double");

                    b.Property<decimal>("OffSet")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Operators")
                        .HasColumnType("int");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Repeat")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("RunTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("SetTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("WarehouseCode")
                        .HasColumnType("varchar(13)");

                    b.Property<string>("WorkControl")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseCode");

                    b.ToTable("OperationTime");
                });

            modelBuilder.Entity("Interno.Production.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Actual")
                        .HasColumnType("int");

                    b.Property<double>("Availability")
                        .HasColumnType("double");

                    b.Property<int?>("BreaksId")
                        .HasColumnType("int");

                    b.Property<double>("Capacity")
                        .HasColumnType("double");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date1")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date2")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<double>("Eficiency")
                        .HasColumnType("double");

                    b.Property<double>("FirstPassYield")
                        .HasColumnType("double");

                    b.Property<DateTime>("InitialTime")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Inprovement")
                        .HasColumnType("double");

                    b.Property<string>("Item")
                        .HasColumnType("longtext");

                    b.Property<double>("LMPU")
                        .HasColumnType("double");

                    b.Property<TimeSpan>("LeadTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("LeaderNumber")
                        .HasColumnType("int");

                    b.Property<double>("OE")
                        .HasColumnType("double");

                    b.Property<double>("OEE")
                        .HasColumnType("double");

                    b.Property<double>("OEE1")
                        .HasColumnType("double");

                    b.Property<TimeSpan>("OperativeTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("Operators")
                        .HasColumnType("int");

                    b.Property<int>("OrderQty")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("OverTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("OverTimeEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlanQty")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("PlanedTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Planner")
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("ProductiveTime")
                        .HasColumnType("time(6)");

                    b.Property<double>("Rate")
                        .HasColumnType("double");

                    b.Property<string>("ResourceCode")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<DateTime>("SMKTDate")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("ScheduledOperatingTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("ScheduledStops")
                        .HasColumnType("time(6)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SubResourceCode")
                        .HasColumnType("varchar(13)");

                    b.Property<int>("SupervisorNumber")
                        .HasColumnType("int");

                    b.Property<double>("TEP")
                        .HasColumnType("double");

                    b.Property<TimeSpan>("TakTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("Updated")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("WHSDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkOrder")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BreaksId");

                    b.HasIndex("ResourceCode");

                    b.HasIndex("ShiftId");

                    b.HasIndex("SubResourceCode");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("Interno.Production.Models.Resource", b =>
                {
                    b.HasBaseType("Interno.Inventory.Models.Warehouse");

                    b.HasDiscriminator().HasValue("Resource");
                });

            modelBuilder.Entity("Interno.Outset.Models.HrxHr", b =>
                {
                    b.HasBaseType("Interno.Production.Models.HourByHour");

                    b.HasDiscriminator().HasValue("HrxHr");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.Break", b =>
                {
                    b.HasOne("Interno.HumanResource.Models.Catalog.BreaksGroup", null)
                        .WithMany("Breaks")
                        .HasForeignKey("BreaksGroupId");

                    b.HasOne("Interno.HumanResource.Models.Catalog.BreakType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.BreaksGroup", b =>
                {
                    b.HasOne("Interno.HumanResource.Models.Catalog.Shift", "Shift")
                        .WithMany("BreaksGroups")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Interno.Inventory.Models.Warehouse", b =>
                {
                    b.HasOne("Interno.Inventory.Models.WarehouseGroup", "Group")
                        .WithMany("Warehouses")
                        .HasForeignKey("GroupId");

                    b.HasOne("Interno.Inventory.Models.WarehouseType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.Domain.Catalog.UM", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitCode");

                    b.Navigation("Group");

                    b.Navigation("Type");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Interno.Production.Models.Downtime", b =>
                {
                    b.HasOne("Interno.Production.Models.HourByHour", null)
                        .WithMany("Downtimes")
                        .HasForeignKey("HourByHourId");

                    b.HasOne("Interno.Production.Models.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.Production.Models.Result", "Result")
                        .WithMany("Downtime")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Interno.Production.Models.HourByHour", b =>
                {
                    b.HasOne("Interno.Production.Models.Result", null)
                        .WithMany("HourByHour")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Interno.Production.Models.Labor", b =>
                {
                    b.HasOne("Interno.Production.Models.Result", "Result")
                        .WithMany("Labor")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Interno.Production.Models.OperationTime", b =>
                {
                    b.HasOne("Interno.Inventory.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseCode");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Interno.Production.Models.Result", b =>
                {
                    b.HasOne("Interno.HumanResource.Models.Catalog.BreaksGroup", "Breaks")
                        .WithMany()
                        .HasForeignKey("BreaksId");

                    b.HasOne("Interno.Production.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.HumanResource.Models.Catalog.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interno.Production.Models.Resource", "SubResource")
                        .WithMany()
                        .HasForeignKey("SubResourceCode");

                    b.Navigation("Breaks");

                    b.Navigation("Resource");

                    b.Navigation("Shift");

                    b.Navigation("SubResource");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.BreaksGroup", b =>
                {
                    b.Navigation("Breaks");
                });

            modelBuilder.Entity("Interno.HumanResource.Models.Catalog.Shift", b =>
                {
                    b.Navigation("BreaksGroups");
                });

            modelBuilder.Entity("Interno.Inventory.Models.WarehouseGroup", b =>
                {
                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("Interno.Production.Models.HourByHour", b =>
                {
                    b.Navigation("Downtimes");
                });

            modelBuilder.Entity("Interno.Production.Models.Result", b =>
                {
                    b.Navigation("Downtime");

                    b.Navigation("HourByHour");

                    b.Navigation("Labor");
                });
#pragma warning restore 612, 618
        }
    }
}
