"""add_companies_schema

Revision ID: 13f1006bf066
Revises: dc2611da6e2c
Create Date: 2026-04-03 22:41:34.749646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f1006bf066'
down_revision: Union[str, None] = 'dc2611da6e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('parent_group_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_group_id'], ['business_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_parent_group_id'), 'companies', ['parent_group_id'], unique=False)
    op.drop_index('ix_ict_company_id', table_name='inter_company_transfers')
    op.drop_index('ix_ict_destination_company_id', table_name='inter_company_transfers')
    op.drop_index('ix_ict_mirror_document_id', table_name='inter_company_transfers')
    op.drop_index('ix_ict_product_id', table_name='inter_company_transfers')
    op.drop_index('ix_ict_status', table_name='inter_company_transfers')
    op.drop_column('inter_company_transfers', 'unit_price_amount')
    op.drop_column('inter_company_transfers', 'cost_b_amount')
    op.drop_column('inter_company_transfers', 'wac_origin_amount')
    op.drop_column('inter_company_transfers', 'revenue_a_amount')
    op.drop_column('inventory_movements', 'unit_price_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('unit_price_amount', sa.NUMERIC(precision=18, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('inter_company_transfers', sa.Column('revenue_a_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True))
    op.add_column('inter_company_transfers', sa.Column('wac_origin_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True))
    op.add_column('inter_company_transfers', sa.Column('cost_b_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True))
    op.add_column('inter_company_transfers', sa.Column('unit_price_amount', sa.NUMERIC(precision=18, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.create_index('ix_ict_status', 'inter_company_transfers', ['status'], unique=False)
    op.create_index('ix_ict_product_id', 'inter_company_transfers', ['product_id'], unique=False)
    op.create_index('ix_ict_mirror_document_id', 'inter_company_transfers', ['mirror_document_id'], unique=False)
    op.create_index('ix_ict_destination_company_id', 'inter_company_transfers', ['destination_company_id'], unique=False)
    op.create_index('ix_ict_company_id', 'inter_company_transfers', ['company_id'], unique=False)
    op.drop_index(op.f('ix_companies_parent_group_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
