"""Initial Schema (from existing)

Revision ID: 42ea522fc124
Revises: 
Create Date: 2026-03-24 17:03:45.325453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ea522fc124'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(name):
    from sqlalchemy import inspect as sa_inspect
    bind = op.get_bind()
    return name in sa_inspect(bind).get_table_names()


def _safe_index(index_name, table_name, columns, **kwargs):
    try:
        op.create_index(index_name, table_name, columns, **kwargs)
    except Exception:
        pass


def _safe_drop_column(table_name, column_name):
    try:
        op.drop_column(table_name, column_name)
    except Exception:
        pass


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists('inventory_stocks'):
        op.create_table('inventory_stocks',
        sa.Column('warehouse_id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('uom_id', sa.UUID(), nullable=False),
        sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('reserved_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('min_stock', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('reorder_point', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column('group_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('transaction_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('version_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('warehouse_id', 'product_id', 'company_id', name='uq_warehouse_product_tenant')
        )
        _safe_index(op.f('ix_inventory_stocks_company_id'), 'inventory_stocks', ['company_id'], unique=False)
        _safe_index(op.f('ix_inventory_stocks_group_id'), 'inventory_stocks', ['group_id'], unique=False)
        _safe_index(op.f('ix_inventory_stocks_product_id'), 'inventory_stocks', ['product_id'], unique=False)
        _safe_index(op.f('ix_inventory_stocks_uom_id'), 'inventory_stocks', ['uom_id'], unique=False)
        _safe_index(op.f('ix_inventory_stocks_warehouse_id'), 'inventory_stocks', ['warehouse_id'], unique=False)

    if not _table_exists('stock_lots'):
        op.create_table('stock_lots',
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('batch_number', sa.String(length=100), nullable=False),
        sa.Column('expiration_date', sa.Date(), nullable=True),
        sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column('group_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('transaction_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('version_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        _safe_index(op.f('ix_stock_lots_batch_number'), 'stock_lots', ['batch_number'], unique=False)
        _safe_index(op.f('ix_stock_lots_company_id'), 'stock_lots', ['company_id'], unique=False)
        _safe_index(op.f('ix_stock_lots_group_id'), 'stock_lots', ['group_id'], unique=False)
        _safe_index(op.f('ix_stock_lots_product_id'), 'stock_lots', ['product_id'], unique=False)

    _safe_drop_column('inter_company_transfers', 'revenue_a_amount')
    _safe_drop_column('inter_company_transfers', 'cost_b_amount')
    _safe_drop_column('inter_company_transfers', 'unit_price_amount')
    _safe_drop_column('inter_company_transfers', 'wac_origin_amount')
    _safe_drop_column('inventory_movements', 'unit_price_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tables = ['stock_lots', 'inventory_stocks']
    for t in tables:
        try:
            op.drop_table(t)
        except Exception:
            pass
    # ### end Alembic commands ###
