"""architecture_cleanup

Revision ID: b866e852ddc4
Revises: 13f1006bf066
Create Date: 2026-04-05 16:48:17.187844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b866e852ddc4'
down_revision: Union[str, None] = '13f1006bf066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual Addition: Create Enums if they don't exist
    op.execute("CREATE TYPE movementtype AS ENUM ('ENTRY', 'OUTPUT', 'TRANSFER', 'ADJUSTMENT')")
    op.execute("CREATE TYPE warehousetype AS ENUM ('PHYSICAL', 'VIRTUAL', 'TRANSIT', 'RESOURCE', 'EXT_PARTNER')")

    op.drop_index('ix_ict_company_id', table_name='inter_company_transfers')
    op.drop_index('ix_ict_destination_company_id', table_name='inter_company_transfers')
    op.drop_index('ix_ict_mirror_document_id', table_name='inter_company_transfers')
    op.drop_index('ix_ict_product_id', table_name='inter_company_transfers')
    op.drop_index('ix_ict_status', table_name='inter_company_transfers')
    op.drop_column('inter_company_transfers', 'revenue_a_amount')
    op.drop_column('inter_company_transfers', 'unit_price_amount')
    op.drop_column('inter_company_transfers', 'cost_b_amount')
    op.drop_column('inter_company_transfers', 'wac_origin_amount')
    op.add_column('inventory_movement_concepts', sa.Column('description', sa.Text(), nullable=True))
    op.execute("ALTER TABLE inventory_movement_concepts ALTER COLUMN type TYPE movementtype USING type::movementtype")
    op.alter_column('inventory_movement_concepts', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint('inventory_movement_concepts_code_key', 'inventory_movement_concepts', type_='unique')
    op.create_index(op.f('ix_inventory_movement_concepts_code'), 'inventory_movement_concepts', ['code'], unique=False)
    op.drop_column('inventory_movements', 'unit_price_amount')
    op.add_column('inventory_warehouses', sa.Column('type', sa.Enum('PHYSICAL', 'VIRTUAL', 'TRANSIT', 'RESOURCE', 'EXT_PARTNER', name='warehousetype'), nullable=False))
    op.add_column('inventory_warehouses', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('inventory_warehouses', 'code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('inventory_warehouses', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_warehouses', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('inventory_warehouses', 'code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('inventory_warehouses', 'description')
    op.drop_column('inventory_warehouses', 'type')
    op.add_column('inventory_movements', sa.Column('unit_price_amount', sa.NUMERIC(precision=18, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_inventory_movement_concepts_code'), table_name='inventory_movement_concepts')
    op.create_unique_constraint('inventory_movement_concepts_code_key', 'inventory_movement_concepts', ['code'])
    op.alter_column('inventory_movement_concepts', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('inventory_movement_concepts', 'type',
               existing_type=sa.Enum('ENTRY', 'OUTPUT', 'TRANSFER', 'ADJUSTMENT', name='movementtype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('inventory_movement_concepts', 'description')
    op.add_column('inter_company_transfers', sa.Column('wac_origin_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True))
    op.add_column('inter_company_transfers', sa.Column('cost_b_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True))
    op.add_column('inter_company_transfers', sa.Column('unit_price_amount', sa.NUMERIC(precision=18, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('inter_company_transfers', sa.Column('revenue_a_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True))
    op.create_index('ix_ict_status', 'inter_company_transfers', ['status'], unique=False)
    op.create_index('ix_ict_product_id', 'inter_company_transfers', ['product_id'], unique=False)
    op.create_index('ix_ict_mirror_document_id', 'inter_company_transfers', ['mirror_document_id'], unique=False)
    op.create_index('ix_ict_destination_company_id', 'inter_company_transfers', ['destination_company_id'], unique=False)
    op.create_index('ix_ict_company_id', 'inter_company_transfers', ['company_id'], unique=False)
    # ### end Alembic commands ###
