# .github/workflows/deploy-backend.yml
name: Deploy Backend to AWS ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/auth_service/**'
      - 'backend/inventory_service/**'
      - 'backend/common/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth_service, inventory_service]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push (Auth)
        if: matrix.service == 'auth_service'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: interno-backend-auth-service
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f backend/auth_service/Dockerfile.prod backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build, Tag, and Push (Inventory)
        if: matrix.service == 'inventory_service'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: interno-backend-inventory-service
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f backend/inventory_service/Dockerfile.prod backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
